In [1]:
import altair as alt
import pandas as pd
import geopandas as gpd # Requires geopandas -- e.g.: conda install -c conda-forge geopandas
alt.data_transformers.enable('json') # Let Altair/Vega-Lite work with large data sets

pass

In [2]:
names = pd.read_csv("dpt2020.csv", sep=";")
names.drop(names[names.preusuel == '_PRENOMS_RARES'].index, inplace=True)
names.drop(names[names.dpt == 'XX'].index, inplace=True)

names.sample(5)

         sexe     preusuel annais  dpt  nombre
2931087     2     LUCIENNE   1914   25      32
1918063     2    ANNE-LISE   1986   85       3
1824552     2       ALYCIA   2003   22       3
792389      1  JEAN-CLAUDE   1941   27      71
1045866     1        LUCAS   2002  971      40

In [3]:
depts = gpd.read_file('departements-version-simplifiee.geojson')

depts.sample(5)

,code,nom,geometry
84,84,Vaucluse,"MULTIPOLYGON (((4.89291 44.36482, 4.90663 44.3..."
24,26,Drôme,"POLYGON ((4.80049 45.29836, 4.8588 45.30895, 4..."
0,01,Ain,"POLYGON ((4.78021 46.17668, 4.79458 46.21832, ..."
78,78,Yvelines,"POLYGON ((2.20059 48.90868, 2.16838 48.89508, ..."
66,66,Pyrénées-Orientales,"POLYGON ((2.16605 42.66392, 2.1762 42.65251, 2..."

In [4]:
# Keep a reference around to the plain pandas dataframe, without geometry data, just in case
just_names = names

names = depts.merge(names, how='right', left_on='code', right_on='dpt')

names.sample(5)

,code,nom,geometry,sexe,preusuel,annais,dpt,nombre
132707,52,Haute-Marne,"POLYGON ((4.67018 48.53189, 4.71801 48.54199, ...",1,ANTOINE,1999,52,10
2991060,69,Rhône,"POLYGON ((4.38808 46.21979, 4.39205 46.26302, ...",2,MARIA,1997,69,3
965164,50,Manche,"POLYGON ((-1.11962 49.35557, -1.11346 49.32795...",1,LÉON,1911,50,64
38255,66,Pyrénées-Orientales,"POLYGON ((2.16605 42.66392, 2.1762 42.65251, 2...",1,ALAIN,1941,66,14
3377238,61,Orne,"POLYGON ((-0.84094 48.75222, -0.81927 48.75413...",2,RAYMONDE,1917,61,16

In [5]:
#objectif 1 : chart des 20 prénoms les plus populaires de 2004
"""
annais : filtrer sur 2004
puis garder que les 20 premiers de nombre
puis faire le chart
"""

'\nannais : filtrer sur 2004\npuis garder que les 20 premiers de nombre\npuis faire le chart\n'

In [6]:
names_2004 = just_names[just_names["annais"]=="2004"]
names_2004.head(10)

       sexe preusuel annais dpt  nombre
10987     1    AARON   2004  02       4
10988     1    AARON   2004  03       3
10989     1    AARON   2004  08       4
10990     1    AARON   2004  12       3
10991     1    AARON   2004  13      11
10992     1    AARON   2004  14       4
10993     1    AARON   2004  21       3
10994     1    AARON   2004  25       4
10995     1    AARON   2004  29       4
10996     1    AARON   2004  31       8

In [7]:
grouped_2004 = names_2004.groupby(['preusuel', 'sexe'], as_index=False).sum(numeric_only=True)

grouped_2004

      preusuel  sexe  nombre
0      AALIYAH     2      29
1        AARON     1     281
2          ABD     1       3
3     ABDALLAH     1      82
4        ABDEL     1      22
...        ...   ...     ...
3633     ZOHRA     2      18
3634     ZORAN     1       3
3635   ZOUMANA     1       3
3636       ZOÉ     2    2280
3637      ZYAD     1      11

[3638 rows x 3 columns]

In [8]:
ordered_2004 = grouped_2004.sort_values(by=["nombre"], ascending=False)

In [9]:
top_20 = ordered_2004.iloc[0:20]

In [10]:
base = alt.Chart(top_20).mark_bar().encode(
    x = 'nombre:Q',
    y =alt.Y('preusuel:N', sort='-x')
)

base

alt.Chart(...)

In [11]:
slider = alt.binding_range(min=1900, max=2020, step=1, name='year:')
year = alt.param(value=2004, bind=slider)
base.add_params(year)

alt.Chart(...)

In [12]:
def table(year): 
    names_2004 = just_names[just_names["annais"]==str(year)]
    grouped_2004 = names_2004.groupby(['preusuel', 'sexe'], as_index=False).sum(numeric_only=True)
    ordered_2004 = grouped_2004.sort_values(by=["nombre"], ascending=False)
    top_20 = ordered_2004.iloc[0:20]
    return top_20

In [13]:
just_names

         sexe preusuel annais  dpt  nombre
10885       1    AADIL   1983   84       3
10886       1    AADIL   1992   92       3
10888       1    AAHIL   2016   95       3
10892       1    AARON   1962   75       3
10893       1    AARON   1976   75       3
...       ...      ...    ...  ...     ...
3727545     2      ZYA   2013   44       4
3727546     2      ZYA   2013   59       3
3727547     2      ZYA   2017  974       3
3727548     2      ZYA   2018   59       3
3727550     2     ZYNA   2013   93       3

[3668274 rows x 5 columns]

In [141]:
just_names_year = just_names.groupby(['annais', 'preusuel', 'sexe'], as_index=False).sum(numeric_only=True)
# just_names_ordered = just_names_year.sort_values(by=["nombre"], ascending=False)


just_names_year.head(20)

   annais   preusuel  sexe  nombre
0    1900       ABEL     1     382
1    1900    ABRAHAM     1       9
2    1900    ACHILLE     1     152
3    1900   ACHILLES     1       4
4    1900       ADAM     1       9
5    1900   ADELAIDE     2     143
6    1900   ADELHEID     2       3
7    1900    ADELINA     2      27
8    1900    ADELINE     2     169
9    1900    ADOLPHE     1     464
10   1900  ADOLPHINE     2      65
11   1900     ADONIS     1       3
12   1900     ADRIEN     1     835
13   1900   ADRIENNE     2    1013
14   1900      ADÈLE     2     626
15   1900     AGATHE     1       3
16   1900     AGATHE     2      62
17   1900      AGLAE     2       9
18   1900      AGNÈS     2     383
19   1900       AIDA     2       3

In [142]:
names = just_names_year

In [16]:
# # The spacing will only show up in your IDE, not on this doc page
# options = ['Europe', 'Japan', 'USA']
# labels = [option + ' ' for option in options]

# input_dropdown = alt.binding_radio(
#     # Add the empty selection which shows all when clicked
#     options=options + [None],
#     labels=labels + ['All'],
#     name='Region: '
# )
# selection = alt.selection_point(
#     fields=['Origin'],
#     bind=input_dropdown,
# )

# alt.Chart(cars).mark_point().encode(
#     x='Horsepower:Q',
#     y='Miles_per_Gallon:Q',
#     # We need to set a constant domain to preserve the colors
#     # when only one region is shown at a time
#     color=alt.Color('Origin:N').scale(domain=options),
# ).add_params(
#     selection
# ).transform_filter(
    # selection
# )

In [143]:
names["annees"] = names["annais"].apply(int)

In [18]:
names.head(10
)

  annais  preusuel  sexe  nombre  annees
0   1900      ABEL     1     382    1900
1   1900   ABRAHAM     1       9    1900
2   1900   ACHILLE     1     152    1900
3   1900  ACHILLES     1       4    1900
4   1900      ADAM     1       9    1900
5   1900  ADELAIDE     2     143    1900
6   1900  ADELHEID     2       3    1900
7   1900   ADELINA     2      27    1900
8   1900   ADELINE     2     169    1900
9   1900   ADOLPHE     1     464    1900

In [19]:
from IPython.display import display, HTML

# 1. Injection du CSS pour modifier l'apparence visuelle globale du slider
display(HTML("""
<style>
    .vega-bind {
        font-size: 18px !important;       /* Augmente la taille du texte de l'étiquette */
        font-family: 'Segoe UI', sans-serif;
        font-weight: 500;
        # color: #333;
        margin-top: 20px;                 /* Espace entre le graphique et le slider */
        margin-bottom: 20px;
    }

    /* Modifier la barre horizontale du slider */
    .vega-bind input[type="range"] {
        width: 500px !important;          /* LARGEUR VISUELLE DU SLIDER (par défaut ~150px) */
        height: 10px;                     /* Épaisseur de la barre du curseur */
        # background: #e0e0e0;
        border-radius: 5px;
        appearance: none;
        cursor: pointer;
        margin-left: 15px;                /* Espace entre le texte et la barre */
        margin-right: 15px;
    }

    /* Modifier le bouton coulissant (la "puce" ou "le bouton rond") du slider */
    .vega-bind input[type="range"]::-webkit-slider-thumb {
        appearance: none;
        width: 20px;                      /* Largeur de la puce */
        height: 20px;                     /* Hauteur de la puce */
        border-radius: 50%;               /* Rend le bouton rond */
        background: #4A90E2;              /* Couleur du bouton */
        cursor: pointer;
    }
</style>
"""))

In [20]:
slider = alt.binding_range(min=1900, max=2020, step=1, name='year:')
year = alt.param(value=2004, bind=slider)
selection = alt.selection_point(fields=["annees"], bind=slider)


# options = [(i) for i in range(1900, 2021)]
# labels = [str(option) + ' ' for option in options]

# input_dropdown = alt.binding_radio(
#     # Add the empty selection which shows all when clicked
#     options=options + [None],
#     labels=[str(i) for i in labels] + ['All'],
#     name='Region: '
# )
# selection = alt.selection_point(
#     fields=['annees'],
#     bind=input_dropdown,
# )


base = alt.Chart(names).mark_bar().encode(
    x = 'nombre:Q',
    y =alt.Y('preusuel:N', sort='-x'),

    
).add_params(
    year
).transform_filter(
    alt.datum.annais == alt.expr.toString(year),
).transform_window(    
    rank ='rank(nombre)',
    sort=[alt.SortField('nombre', order='descending')]
).transform_filter(
    alt.datum.rank <=20
).properties(
    width=600,
    height=400
)

base

alt.Chart(...)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.cm as cm
import matplotlib.colors as mcolors

def ajouter_couleurs_etendues(df_input):
    df = df_input.copy()
    
    df['sexe'] = df['sexe'].astype(str).str.strip()
    df['preusuel'] = df['preusuel'].astype(str).str.strip()
    
    valeurs_sexes = df['sexe'].unique()
    valeur_garcon = "1" if "1" in valeurs_sexes else "M"
    valeur_fille = "2" if "2" in valeurs_sexes else "F"
    
    unique_boys = df[df['sexe'] == valeur_garcon]['preusuel'].unique()
    unique_girls = df[df['sexe'] == valeur_fille]['preusuel'].unique()
    
    cmap_hommes = mcolors.LinearSegmentedColormap.from_list(
        "BleuVert", ["#1e3c72", "#2a5298", "#00c6ff", "#0072ff", "#11998e", "#38ef7d"]
    )
    
    cmap_femmes = mcolors.LinearSegmentedColormap.from_list(
        "VioletRose", ["#4e54c8", "#b92b27", "#f857a6", "#ff5858", "#ee0979", "#ff6a00"]
    )
    
    dict_couleurs = {}
    
    nb_g = len(unique_boys)
    for i, prenom in enumerate(unique_boys):
        position = i / max(1, nb_g - 1)
        dict_couleurs[(prenom, valeur_garcon)] = mcolors.to_hex(cmap_hommes(position))
        
    nb_f = len(unique_girls)
    for i, prenom in enumerate(unique_girls):
        position = i / max(1, nb_f - 1)
        dict_couleurs[(prenom, valeur_fille)] = mcolors.to_hex(cmap_femmes(position))
        
    df['couleur'] = df.apply(lambda row: dict_couleurs.get((row['preusuel'], row['sexe']), "#888888"), axis=1)
    
    return df

In [30]:
import colorsys

def generer_couleurs_eloignees(n, clarte=0.5, saturation=0.8):
    """
    Génère n couleurs spectralement distantes.
    
    :param n: Nombre de couleurs souhaitées.
    :param clarte: Une valeur unique (ex: 0.5) ou une liste/tuple de valeurs (ex: [0.4, 0.7]) 
                   pour faire varier la luminosité.
    :param saturation: Saturation des couleurs (entre 0.0 et 1.0).
    :return: Liste de codes couleur Hexadécimaux.
    """
    couleurs = []
    
    for i in range(n):
        # Division égale du cercle chromatique (Teinte entre 0.0 et 1.0)
        teinte = i / n
        
        # Gestion de la clarté (fixe ou alternée)
        if isinstance(clarte, (list, tuple)):
            c = clarte[i % len(clarte)]  # Alterne entre les clartés fournies
        else:
            c = clarte
            
        # Conversion HSL (HLS en Python) vers RGB (valeurs entre 0.0 et 1.0)
        r, g, b = colorsys.hls_to_rgb(teinte, c, saturation)
        
        # Conversion en format Hexadécimal (#RRGGBB)
        hex_color = f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"
        couleurs.append(hex_color)
        
    return couleurs

In [38]:
def make_lst_couleurs(df_input):
    df = df_input.copy()

    prenoms_fille = df[df["sexe"]==2]["preusuel"].unique().tolist()
    prenoms_garcon = df[df["sexe"]==1]["preusuel"].unique().tolist()
    print(prenoms_fille)
    print(prenoms_garcon)
    prenoms = prenoms_fille + prenoms_garcon
    n = len(prenoms)
    lst_couleurs = generer_couleurs_eloignees(n, [0.3, 0.6, 0.9], 0.8)
    
    return lst_couleurs



def make_dico_couleurs(prenoms, prenoms_fille, prenoms_garcon, lst_couleurs): 
    dico = {}
    for i in range(len(prenoms)): 
        if i<len(prenoms_fille):
            dico[prenoms_fille[i], 2] = lst_couleurs[i]
        else : 
            dico[prenoms_garcon[i - len(prenoms_fille)], 1] = lst_couleurs[i]
    return dico

In [39]:
lst_couleurs = make_lst_couleurs(names)

['ADELAIDE', 'ADELHEID', 'ADELINA', 'ADELINE', 'ADOLPHINE', 'ADRIENNE', 'ADÈLE', 'AGATHE', 'AGLAE', 'AGNÈS', 'AIDA', 'AIMÉE', 'ALBANIE', 'ALBERTA', 'ALBERTE', 'ALBERTINE', 'ALBINE', 'ALEXANDRINE', 'ALEXIA', 'ALEXINA', 'ALEXINE', 'ALFREDA', 'ALFREDINE', 'ALICE', 'ALIDA', 'ALINE', 'ALIX', 'ALIXE', 'ALLIETTE', 'ALPHENA', 'ALPHONSINE', 'ALZIRE', 'AMALIE', 'AMANDA', 'AMANDINE', 'AMBROISINE', 'AMÉLIA', 'AMÉLIE', 'ANAISE', 'ANASTASIE', 'ANAÏS', 'ANDREANNE', 'ANDRÉ', 'ANDRÉA', 'ANDRÉE', 'ANGE', 'ANGELA', 'ANGELINA', 'ANGELINE', 'ANGELIQUE', 'ANGÈLE', 'ANITA', 'ANNA', 'ANNE', 'ANNE-MARIE', 'ANNETTE', 'ANNITA', 'ANNONCIA', 'ANNONCIADE', 'ANTHELMETTE', 'ANTHELMINE', 'ANTOINETTE', 'ANTOINISE', 'ANTONIA', 'ANTONIE', 'ANTONINE', 'APOLLINE', 'APOLLONIE', 'APPOLINE', 'APPOLONIE', 'ARGENTINE', 'ARLETTE', 'ARMANCE', 'ARMANDE', 'ARMANDINE', 'ARMANTINE', 'ARSENE', 'ARTHEMISE', 'ASSOMPTION', 'ASSUNTA', 'AUGUSTA', 'AUGUSTINA', 'AUGUSTINE', 'AURORE', 'AURÉLIE', 'AZELINE', 'AZEMA', 'BABETTE', 'BAPTISTINE', 'BARBARA', 'BARBE', 'BASTIENNE', 'BATHILDE', 'BEATRIX', 'BENEDICTE', 'BENJAMINE', 'BENOITE', 'BERENGERE', 'BERNADETTE', 'BERNADINE', 'BERNARDE', 'BERNARDINE', 'BERTHA', 'BERTHE', 'BERTHILDE', 'BERTILLE', 'BERTRANDE', 'BLAISE', 'BLANCHE', 'BLANDINE', 'BONAVENTURE', 'BONIFACE', 'BONNE', 'BRIGITTE', 'BÉATRICE', 'CAMILLE', 'CAMÉLIA', 'CARMELE', 'CARMELITE', 'CARMEN', 'CAROLINE', 'CATHERINE', 'CELENIE', 'CELESTE', 'CELESTINE', 'CELIE', 'CELINA', 'CELINIE', 'CESARINE', 'CHARLINE', 'CHARLOTTE', 'CHRISTIANE', 'CHRISTINE', 'CLADIE', 'CLAIRE', 'CLARA', 'CLARISSE', 'CLAUDIA', 'CLAUDINE', 'CLELIE', 'CLORINDE', 'CLOTHILDE', 'CLOTILDE', 'CLÉMENCE', 'CLÉMENTINE', 'COLETTE', 'COLOMBE', 'CONCEPTION', 'CONSTANCE', 'CORALIE', 'CORENTINE', 'CORNELIE', 'CÉCILE', 'CÉCILIA', 'CÉLINE', 'DARIA', 'DELE', 'DELPHINE', 'DENISE', 'DESIREE', 'DIDIER', 'DINA', 'DOLORES', 'DOMINICA', 'DOMINIQUE', 'DONATIENNE', 'DORIA', 'DOROTHEE', 'DOROTHY', 'EDITH', 'EDITHE', 'EDMEE', 'EDMONDE', 'EDWIGE', 'EGLANTINE', 'ELEONORE', 'ELFRIEDE', 'ELIA', 'ELIANE', 'ELINA', 'ELISA', 'ELISABETH', 'ELISABETHE', 'ELISE', 'ELIZABETH', 'ELLA', 'ELLEN', 'ELMIRE', 'ELODIE', 'ELOISE', 'ELSA', 'ELSE', 'ELVINA', 'ELVIRE', 'ELZA', 'EMELIA', 'EMELIE', 'EMERANCE', 'EMILIA', 'EMILIE', 'EMILIENNE', 'EMMA', 'EMME', 'EMMELIE', 'ENGRACE', 'ERNA', 'ERNESTINE', 'ESPERANCE', 'ESTELLA', 'ESTELLE', 'ESTHER', 'ETIENNETTE', 'ETIENNISE', 'EUDOXIE', 'EUGENIA', 'EUGÉNIE', 'EULALIE', 'EUPHEMIE', 'EUPHRASIE', 'EUSEBIE', 'EVA', 'EVARISTE', 'EVE', 'EVELINE', 'EVODIE', 'EZILDA', 'FABIENNE', 'FANELIE', 'FANNY', 'FAUSTINE', 'FELICIA', 'FELICIE', 'FELICIENNE', 'FELICITE', 'FELIXIA', 'FERDINANDE', 'FERNANDE', 'FIDELINE', 'FIRMINE', 'FLAVIE', 'FLEURINE', 'FLORA', 'FLORE', 'FLORENCE', 'FLORENTINE', 'FLORESTINE', 'FLORINE', 'FORTUNEE', 'FRANCE', 'FRANCELINE', 'FRANCIA', 'FRANCINE', 'FRANCISCA', 'FRANÇOIS', 'FRANÇOISE', 'FRIDA', 'FRIEDA', 'FRÉDÉRIQUE', 'FÉLIX', 'GABRIELLE', 'GENEVIÈVE', 'GEORGETTE', 'GEORGINA', 'GEORGINE', 'GERMAINE', 'GERTRUDE', 'GHISLAINE', 'GILBERTE', 'GISELLE', 'GISÈLE', 'GLADIE', 'GRACE', 'GRACIANNE', 'GRACIEUSE', 'GRATIANNE', 'GUILLAUMETTE', 'GUILLAUMINE', 'GUILLEMETTE', 'GUSTAVIE', 'HEDWIG', 'HEDWIGE', 'HELENA', 'HENRIA', 'HENRIETTA', 'HENRIETTE', 'HERMANCE', 'HERMINE', 'HERMINIE', 'HERVELINE', 'HILDE', 'HILDEGARDE', 'HONORINE', 'HORTENSE', 'HORTENSIA', 'HUGUETTE', 'HYACINTHE', 'HÉLOÏSE', 'HÉLÈNE', 'IDA', 'IGNACE', 'INNOCENTE', 'INÈS', 'IRENEE', 'IRMA', 'IRÈNE', 'ISABELLE', 'ISAURE', 'ISBERGUE', 'ISMERIE', 'IVONNE', 'JACQUELINE', 'JANE', 'JEAN', 'JEANNE', 'JEANNE-MARIE', 'JEANNETTE', 'JEANNIE', 'JEANNINE', 'JENNY', 'JEROMINE', 'JOANNA', 'JOSEPHE', 'JOSEPHINE', 'JUDITH', 'JULIA', 'JULIANA', 'JULIE', 'JULIENNE', 'JULIETTE', 'JUSTINA', 'JUSTINE', 'LATCHIMY', 'LAURE', 'LAURENCE', 'LAURENCIE', 'LAURENTINE', 'LAZARETTE', 'LAZARINE', 'LEOCADIE', 'LEONA', 'LEONARDE', 'LEONCE', 'LEONCIA', 'LEONCIE', 'LEONIDE', 'LEONNE', 'LEOPOLDINE', 'LETITIA', 'LIANE', 'LILLY', 'LILY', 'LINA', 'LINE', 'LISE', 'LOETITIA', 'LOUISA', 'LOUISE', 'LUCE', 'LUCETTE', 'LUCIA', 'LUCIE', 'LUCIENNE', 'LUCILE', 'LUCINE', 'LUCY', 'LUDIVINE', 'LYDIA', 'LYDIE', 'LÉA', 'LÉONE', 'LÉONIE', 'LÉONTINE', 'MADELAINE', 'MADELEINE', 'MAGDELAINE', 'MAGDELEINE', 'MALVINA', 'MARCELINE', 'MARCELLE', 'MARCELLINE', 'MARGUERITE', 'MARGUERITTE', 'MARIA', 'MARIANNE', 'MARIAYE', 'MARIE', 'MARIE-ANGE', 'MARIE-ANNE', 'MARIE-ANTOINETTE', 'MARIE-EUGÉNIE', 'MARIE-FRANÇOISE', 'MARIE-JEANNE', 'MARIE-JOSEPH', 'MARIE-JOSEPHINE', 'MARIE-LOUISE', 'MARIE-LUCIE', 'MARIE-MADELEINE', 'MARIE-ROSE', 'MARIE-THEREZE', 'MARIE-THÉRÈSE', 'MARIETTE', 'MARILIS', 'MARINE', 'MARTHA', 'MARTHE', 'MARTINE', 'MARY', 'MATHEA', 'MATHEE', 'MATHILDE', 'MATHURINE', 'MAXELLENDE', 'MAXENCE', 'MAXIME', 'MAXIMILIENNE', 'MERCEDES', 'META', 'MICHELINE', 'MICHELLE', 'MINA', 'MIREILLE', 'MODESTE', 'MODESTINE', 'MONIQUE', 'MÉLANIE', 'MÉLINA', 'NADEGE', 'NANCY', 'NATALIE', 'NATALINE', 'NATHALIE', 'NELIE', 'NELLY', 'NOELE', 'NOELIE', 'NOELINE', 'NOELLA', 'NOEMI', 'NOEMIE', 'NONCE', 'NONCIADE', 'NOYALE', 'NOËLLE', 'OCTAVIE', 'OCULINE', 'ODETTE', 'ODILE', 'OLGA', 'OLIPHIE', 'OLIVE', 'OLIVIA', 'OLYMPE', 'ORPHA', 'ORPHINA', 'PALMYRE', 'PASCALINE', 'PASQUINE', 'PAULA', 'PAULE', 'PAULETTE', 'PAULINA', 'PAULINE', 'PELAGIE', 'PEROLINE', 'PERONNE', 'PERRINE', 'PETRONILLE', 'PHILIBERTE', 'PHILIPPE', 'PHILIPPINE', 'PHILOMENE', 'PIERRE', 'PIERRETTE', 'PIERRINE', 'PLACIDIE', 'PONAMA', 'PRUDENCE', 'PULCHERIE', 'RACHEL', 'RACHELLE', 'RADEGONDE', 'RAIMONDE', 'RAPHAELLE', 'RAYMONDE', 'REBECCA', 'REGINA', 'REINE', 'RENELIA', 'RENELLE', 'RENÉE', 'REPARATE', 'RESTITUDE', 'ROBERTINE', 'ROLANDE', 'ROLLANDE', 'ROMAINE', 'ROMANIE', 'ROSA', 'ROSALIE', 'ROSANGE', 'ROSE', 'ROSELINE', 'ROSELLA', 'ROSINA', 'ROSINE', 'RÉGINE', 'RÉMY', 'SABINE', 'SAINTE', 'SALOMEE', 'SALOMÉ', 'SARA', 'SARAH', 'SATURNIN', 'SCHOLASTIQUE', 'SEBASTIENNE', 'SERAPHIE', 'SERAPHINE', 'SEVERINE', 'SIDONIE', 'SILVINE', 'SIMONE', 'SIMONNE', 'SOLANGE', 'SONIA', 'SOPHIE', 'STANISLAS', 'STÉPHANIE', 'SUSANNE', 'SUZANNE', 'SYLVAINE', 'SYLVANIE', 'SYLVIA', 'SYLVIE', 'THEOBALDINE', 'THEODORE', 'THEODORINE', 'THERESA', 'THERESINE', 'THEREZE', 'THOMASSINE', 'THÉRÈSE', 'TOUSSAINTE', 'TOUSSINE', 'URANIE', 'URSULE', 'VALENTINE', 'VALERINE', 'VALLIAMEE', 'VALÉRIE', 'VICTOIRE', 'VICTORIA', 'VICTORINE', 'VINCENTE', 'VINCINE', 'VIOLETTE', 'VIRGINA', 'VIRGINIE', 'VITALINE', 'VIVIANE', 'VIVIENNE', 'VÉRONIQUE', 'WILHELMINE', 'XAVIERE', 'YOLANDE', 'YVETTE', 'YVONNE', 'ZELIA', 'ZELIE', 'ZENAIDE', 'ZENOBIE', 'ZOÉ', 'ZULMA', 'ADELIA', 'ADELPHINE', 'AGLAEE', 'AIMA', 'ALCIDIE', 'ALICIA', 'ALMA', 'ALODIE', 'AMANTE', 'AMELINA', 'ANDRELINE', 'ANTOINE', 'APPOLINA', 'ARMELLE', 'AUGUSTE', 'BARBERINE', 'BERANGERE', 'CALIXTE', 'CANDIE', 'CLORINTHE', 'DANIELLE', 'DARIE', 'DEA', 'DELICE', 'DENYSE', 'DEVOTE', 'DIANE', 'DOMINIQUETTE', 'DOMITILDE', 'DORA', 'EDITE', 'EGLEE', 'ELENE', 'ELINE', 'EMELINA', 'EMERENCE', 'EMILA', 'ERICA', 'ETIENNA', 'EUPHROISIE', 'EUPHROSINE', 'EVELINA', 'FAUSTIN', 'FLEURIE', 'FRUMENCE', 'GRACIE', 'GRACIETTE', 'GRATIENNE', 'GRÉGOIRE', 'GUILHERMINE', 'HILDEGARD', 'HONOREE', 'IRENA', 'JACQUEMINE', 'JACQUETTE', 'JANINE', 'JEANINE', 'JEANNY', 'JOACHIM', 'JOSEPH', 'LAURA', 'LAURENCINE', 'LAURENTIE', 'LAURETTE', 'LIBRE', 'LILIANE', 'LISA', 'LISETTE', 'LOUISETTE', 'LUCRECE', 'LÉANDRE', 'MAGLOIRE', 'MARDAYE', 'MARIE-BERTHE', 'MARIE-CLAIRE', 'MARIE-CÉCILE', 'MARIE-DOMINIQUE', 'MARIE-JOSEPHE', 'MARIE-JULIE', 'MARIE-LÉONIE', 'MARIE-MARGUERITE', 'MARIE-MARTHE', 'MARIE-SAINTE', 'MARIE-VIRGINIE', 'MARIETTA', 'MARIUCCIA', 'MAURICETTE', 'MAURICIA', 'MAY', 'MEDALINE', 'MINATCHY', 'MINNA', 'NARCISSE', 'NEREE', 'NICOLAS', 'NICOLE', 'NICOLETTE', 'NOELA', 'NOELISE', 'OMERINE', 'ORANCIE', 'PALMA', 'PAMPHILIA', 'PAQUERETTE', 'PASCALE', 'PROVIDENCE', 'REGIA', 'REJANE', 'REMICIA', 'RENELDE', 'ROSELIA', 'ROSEMONDE', 'RUFFINE', 'RUFINE', 'SAGRA', 'SIMON', 'STELLA', 'SUZETTE', 'THEODORA', 'THEODOSE', 'THEOLINE', 'THUMETTE', 'TREPHINE', 'TRINITE', 'VICTOR', 'VINCENTINE', 'YVONE', 'ZULMEE', 'ADOLIE', 'AIMMEE', 'ALEXANDRA', 'ALFREDE', 'ALSACE', 'ALZINA', 'AMANDE', 'AMEDEE', 'AMICIE', 'ANASTHASIE', 'ATHENAIS', 'AVRILLETTE', 'BLAISINE', 'CARMELINE', 'CESARIE', 'CHARLESIA', 'CHARLETTE', 'CHARLISE', 'CLAUDE', 'CONSTANTINE', 'CYPRIENNE', 'CYRILLIA', 'DAMIENNE', 'DELLE', 'ELIDA', 'ERIKA', 'ETIENNE', 'FRANCISE', 'FRIEDE', 'FRÉDÉRIC', 'GASPARINE', 'GEORGES', 'GUSTAVINE', 'HENRILIA', 'HERTHA', 'HILDA', 'ILSE', 'IREINE', 'JEROME', 'JOSEPHA', 'JULINA', 'LAURENCIA', 'LAURINE', 'LEONIA', 'LEONINE', 'LEONISE', 'LIA', 'LILLINE', 'LOETIZIA', 'LUCILLE', 'MACAIRE', 'MAGALI', 'MARIE-AUGUSTINE', 'MARIE-CATHERINE', 'MARIE-GERMAINE', 'MARIE-HÉLÈNE', 'MARILYS', 'MARYLIS', 'MELIE', 'MICHEL', 'NICAISE', 'ORPHISE', 'PERINE', 'PHARAILDE', 'PHILOGONE', 'PIE', 'PROSPERINE', 'ROSE-MARIE', 'ROSIA', 'RUTH', 'SAINT', 'SIMEONIE', 'SYDONIE', 'SYLVINA', 'SYLVINE', 'THAIS', 'THEKLA', 'THERESIA', 'ALDEGONDE', 'ALVINA', 'ANGELLE', 'ANNIE', 'AURELIA', 'AUXILIA', 'BENOÎT', 'BERTHILE', 'BLEUETTE', 'BRUNE', 'CAMILLA', 'CARMELLE', 'CHARLERINE', 'CHRISTIANNE', 'CONSTANT', 'DAVILIA', 'DOMENICA', 'DORETTE', 'ELEONA', 'ELIZA', 'ELVIA', 'EMERANTINE', 'ESTELLIE', 'FLORIA', 'GENEVIEVRE', 'GERARDINE', 'GERVAISE', 'GODELEINE', 'HENRICIE', 'HERMENEGILDE', 'IRMGARD', 'ISIDORE', 'JULICIA', 'LEZINE', 'LOUISIA', 'MARIE-GABRIELLE', 'MARIE-YVONNE', 'MATHIEU', 'MUGUETTE', 'MURIEL', 'ODELIE', 'OPPORTUNE', 'PALMIRE', 'PASQUALINE', 'PATRICE', 'PERROLINE', 'QUITTERIE', 'REYMONDE', 'ROBERTE', 'ROSALINDE', 'ROSETTE', 'SACRA', 'SILVIE', 'SYLVESTINE', 'TATIANA', 'THEODULE', 'VENERANDE', 'VINCIENNE', 'ZITA', 'ABELINE', 'ALIETTE', 'ALINA', 'ALVINE', 'ANGELLA', 'ANNECY', 'ANNICK', 'ANNONCIATION', 'ARISTA', 'AZELIE', 'BRUNETTE', 'CASIMIR', 'CREPIN', 'DALILA', 'ELIETTE', 'ELISEE', 'EMMANUELLE', 'EMMELINE', 'ERMINIE', 'FERNANDINE', 'FLORIDA', 'FORTUNA', 'GAETANE', 'GONTRAND', 'HERTA', 'INGEBORG', 'IVONE', 'JEANE', 'JOSETTE', 'LEONORE', 'LIDIA', 'LISELOTTE', 'LUCINA', 'LUDWINE', 'LÉON', 'MARTHINE', 'NATALINA', 'OBELINE', 'ODILLE', 'PAUL', 'REMISE', 'RENÉ', 'ROMUALD', 'ROSELINDE', 'SIMEONNE', 'SOSTHENE', 'THOMASINE', 'ADA', 'AGNESE', 'ALISE', 'AMY', 'ARTEMISE', 'BERTILE', 'BLUETTE', 'CEPHISE', 'CHERIE', 'CHRISTIENNE', 'CLAUDETTE', 'ELIANNE', 'ESTHERE', 'EULOGE', 'FIRMA', 'GABRIELE', 'GASTON', 'GONTRAN', 'GUILLAUME', 'HERMENCE', 'HILAIRE', 'HILARION', 'IDALIE', 'ILDA', 'JULIENNA', 'LERIA', 'LETIZIA', 'LOUIS', 'MARTINA', 'MAURICE', 'MAURICIENNE', 'NELLIE', 'OTTILIE', 'PADOUE', 'PEPIN', 'PERINA', 'PERPETUE', 'PERRINA', 'RAPHAËL', 'RICHARDE', 'SANTINA', 'STÉPHANE', 'SUZANE', 'SYLVIANE', 'TIBURCE', 'VASTIE', 'ZILDA', 'ALBERT', 'ALWINE', 'AMANTINE', 'AMEDINE', 'ANATOLIE', 'ANATOLINE', 'ANNAIS', 'ANSELME', 'APPOLINAIRE', 'APPOLLONIE', 'ARCADE', 'AUREA', 'AURELIENNE', 'BARNABE', 'BENJAMIN', 'CLARICE', 'CLAUDIE', 'CLEMENCIA', 'COME', 'DANIELE', 'ELIANA', 'EMA', 'EMILE', 'ENA', 'FELICITEE', 'FLORIMONDE', 'FLORINA', 'FLORISE', 'GILLETTE', 'GRAZIELLA', 'IRMINE', 'JACQUEMINETTE', 'JONAS', 'LORRAINE', 'LUC', 'MOISE', 'NADINE', 'NINA', 'OLIVA', 'ORASIE', 'PARFAITE', 'PARVEDY', 'PASCALIE', 'PASSIONISE', 'PAULIA', 'PILAR', 'RELIQUE', 'RICHARDINE', 'ROGATIENNE', 'ROSITA', 'SCHOLASTIE', 'SCOLASTIQUE', 'SIMPLICE', 'VALERIENNE', 'VENUS', 'VINCENT', 'ZELIMA', 'ALPHONSIA', 'AMANTHE', 'CHARLES', 'CRESCENT', 'DOROTHE', 'EDGARD', 'EDOUARLISE', 'EMMY', 'FAUSTINA', 'FIDELE', 'GERDA', 'GINA', 'HELLENE', 'HERMINA', 'IMELDA', 'INNOCENT', 'IRMGARDE', 'IVETTE', 'JOSEFA', 'MANUELLE', 'MARGOT', 'MARINETTE', 'MAUD', 'MESMIN', 'MICHÈLE', 'NADIA', 'PHANELIE', 'RAPHAELA', 'RENETTE', 'RINA', 'SATURNINE', 'SELMA', 'SERGE', 'SERVAIS', 'SUZANNA', 'THEODOSIE', 'THEOPHILE', 'URBAINE', 'VALERE', 'YVONNA', 'ANATOLE', 'ANDREZE', 'ARTHURINE', 'ATHANASIE', 'BERTILDE', 'CRISTINE', 'DENIZE', 'EDMA', 'ELIE', 'EMMANUEL', 'EMMI', 'EUGÈNE', 'EUSTASIE', 'FLEURE', 'FRANCINA', 'FRUCTUEUX', 'GAËTAN', 'GEMMA', 'GLADYS', 'GOLDA', 'GYSELE', 'HELYETT', 'HOSANNA', 'HUGUES', 'LAZARE', 'LILIAN', 'LILLA', 'LUDOVIQUE', 'MARTIALINE', 'MONICA', 'NICOLLE', 'NICOMEDE', 'OPTAT', 'PASCAL', 'PLACIDE', 'RICHARD', 'ROBERT', 'ROMAIN', 'SYLVESTRE', 'VENANCE', 'VERA', 'ZEPHIRINE', 'ANNELIESE', 'APOLONIE', 'BLONDINE', 'BRUNHILDE', 'BRUNO', 'COLLETTE', 'ELFRIDE', 'ELLI', 'ELWIRE', 'ENOGAT', 'ERMINE', 'FLORETTE', 'GABIN', 'GASTONIA', 'GILETTE', 'GODELIEVE', 'GUY', 'JEHANNE', 'JOSEPHTE', 'LAURETTA', 'LEONARD', 'LIE', 'LIESELOTTE', 'LIVIE', 'MAMERT', 'MYRIAM', 'NOELLIE', 'SABAS', 'SAMSON', 'SULPICE', 'SYMPHORIENNE', 'THOMAS', 'URBAIN', 'VICENTA', 'VINCENNE', 'AMOUR', 'ANDRESE', 'ANNECIE', 'APOLLINAIRE', 'ARMIDE', 'BERTHEA', 'CAMILLIA', 'CESAIRE', 'CLET', 'DANIEL', 'DEL', 'ELVIRA', 'ERNEST', 'FIDELIA', 'FLEURICE', 'GILBERTHE', 'GRACY', 'HELIANE', 'HUBERTE', 'JACQUES', 'LAURENTE', 'LIBERTE', 'LOUISIANE', 'MANUELA', 'MARCELLA', 'MATTEA', 'NOELLISE', 'PIERINA', 'PROSPER', 'RAOUL', 'REJANNE', 'SEPTIME', 'SÉBASTIEN', 'YOLAINE', 'AVIT', 'BASILE', 'BENEDICTA', 'BERNARD', 'BERNARDETTE', 'BRICE', 'CARMELLA', 'CHRISTOPHE', 'CLOTAIRE', 'CLOUD', 'CYR', 'EDESE', 'ELISENE', 'ELLY', 'EMERANTE', 'EPIPHANE', 'ERIQUE', 'FIRMIN', 'GASTONNE', 'GEORGE', 'GERTRUD', 'GINETTE', 'GRATIEUSE', 'GUSTAVE', 'GÉRARD', 'HENRI', 'HIPPOLYTE', 'HONORA', 'HONORAT', 'ITALIA', 'JOHANNA', 'JOSEE', 'LAURIANNE', 'LILLI', 'LOTTE', 'MARIE-SUZANNE', 'MERY', 'NATHALINE', 'NICEPHORE', 'ONESIME', 'RAPHAELE', 'RIGOBERT', 'SYLVERE', 'THIMOTHEE', 'TOUSSAINT', 'YVES', 'ZENA', 'ANNEMARIE', 'APOLINE', 'CARMELIA', 'ERMINIA', 'EUSEBE', 'EUSTACHE', 'FELIXINE', 'IRIS', 'JOASSINE', 'LIDIE', 'LIESE', 'LIVIA', 'LORENA', 'MANON', 'MARGARET', 'MARIE-ALICE', 'MARIE-ANNA', 'MARIE-EMILIENNE', 'MARIE-REINE', 'MEDARD', 'MIRELLA', 'NELLA', 'NESTORINE', 'NORA', 'PELAGIA', 'PIA', 'PRISCA', 'RITA', 'ROCH', 'THEOTINE', 'ANATHILDE', 'ANDOCHE', 'ANNELISE', 'ATHANASE', 'AUBIN', 'BRUNA', 'CARME', 'CELIANE', 'CUNEGONDE', 'DORIS', 'ELDA', 'GABY', 'GATIENNE', 'GEOFFROY', 'GISLAINE', 'GODELIVE', 'HUBERTINE', 'IOLANDE', 'ISMENE', 'JOCELYNE', 'JULITTE', 'LANDRY', 'MAURILLE', 'MEDEA', 'MERINA', 'MIREILLA', 'NELLI', 'NORBERT', 'NOËL', 'OLIDA', 'PERVENCHE', 'PIERRINA', 'RAYMOND', 'ROXANE', 'SAINT-ANGE', 'SAINTE-CROIX', 'SEVERIN', 'SIMEONE', 'SYMPHORINE', 'THEOTIME', 'VALERY', 'WENCESLAS', 'YVELINE', 'ACHILLE', 'ADOLPHE', 'ANICET', 'AUGUSTIN', 'BERTHILIE', 'BERTINA', 'DAVIDE', 'EDOUARD', 'EUNICE', 'FRUCTUEUSE', 'GILDA', 'GUERINA', 'HELYETTE', 'LILIANNE', 'LORETTE', 'MALCIE', 'MARIELLE', 'MAXIMILIA', 'MEROPE', 'NORMA', 'OCULI', 'PARFAIT', 'YOLANDA', 'YVONNETTE', 'ZEA', 'ABEL', 'ABELLE', 'ANNIC', 'ARISTIDE', 'CECILLE', 'CYRIAQUE', 'DAVID', 'ELISCA', 'EVELYNE', 'FLAVIEN', 'FLORELLE', 'GERVAIS', 'GILBERT', 'JOACHINE', 'JOAQUINA', 'JOFFRETTE', 'JOFFRINE', 'LORETTA', 'LUDOVIC', 'MARCIENNE', 'MAXIMA', 'MODERAN', 'RITTA', 'ROGER', 'ROSANE', 'AMINA', 'AMPARO', 'ANICETTE', 'BASILIA', 'CHARLEMAGNE', 'ELENA', 'EUSTASE', 'FERLANDE', 'GERVILLIA', 'INCARNATION', 'MARIVONNE', 'NAIDA', 'OLIVIENNE', 'SERGINE', 'TIBURCIA', 'VINCILIA', 'ANITE', 'BETTINA', 'DAISY', 'HUBERT', 'MARIOTTE', 'MEDERIC', 'MOISETTE', 'OMER', 'RÉMI', 'SILVERE', 'TIMOTHÉE', 'VICENTE', 'VIRAMAN', 'ABDON', 'ABDONIE', 'ALCIDA', 'ANGELIA', 'AUBERTINE', 'BERTINE', 'BETTY', 'CHANTAL', 'CLEMIRE', 'DOLLY', 'FRANCETTE', 'GUALBERT', 'HELGA', 'HELIETTE', 'HILDEVERT', 'JOSÉPHINE', 'LEONCINE', 'LYLIANE', 'MYRIAME', 'RUPHINE', 'VENANT', 'VENANTE', 'WILFRID', 'ZACHARIE', 'ALEXIS', 'AMBROISE', 'AMELINE', 'ARTHUR', 'FATMA', 'FIACRE', 'IVA', 'JANNINE', 'LINDA', 'NOEMA', 'PANDIALE', 'RAPHAELLA', 'REINETTE', 'WANDA', 'ALFRÉDA', 'ALYETTE', 'ANDRESINE', 'ASCENSION', 'BARTHELEMY', 'CASIMIRA', 'CLAIRETTE', 'DONAT', 'FULBERT', 'GERMINA', 'GUISLAINE', 'HENRIANNE', 'INESSE', 'JANNE', 'LATIMY', 'LILI', 'LIN', 'LOLA', 'LUCIEN', 'LYSIANE', 'MARIE-EMILIE', 'MARYSE', 'MARYVONNE', 'MATHIAS', 'MERYEM', 'MICHAELLA', 'PASSIONNISE', 'PATRICIA', 'PIERETTE', 'RENA', 'SILVIANE', 'SOLEDAD', 'SUZEANNE', 'SUZY', 'VIVIANNE', 'BABYLAS', 'BRONISLAWA', 'CLÉMENT', 'CONCHITA', 'COSETTE', 'ELOI', 'EPIPHANIE', 'ERNESTE', 'FLORIANE', 'FRANCES', 'GUILLERMINE', 'HELEINE', 'JOSSELINE', 'JUANA', 'LILIA', 'MAFALDA', 'MARIE-CHRISTINE', 'MARIE-HENRIETTE', 'MARIE-SIMONE', 'MARTIALISE', 'PROSPERE', 'STANISLAWA', 'SUZEL', 'WILFRIDE', 'ADINE', 'AGNAN', 'ANNIK', 'ANNY', 'CARMENE', 'CYPRIEN', 'ERITA', 'FAUSTE', 'FELISE', 'FLORENTIN', 'GENTILLE', 'GIZELE', 'ILDEVERT', 'JEANNINA', 'JUANITA', 'LEODA', 'LEONTE', 'MARIE-FRANCE', 'MARIE-MAGDELEINE', 'MARIE-NOËL', 'MIGNONNETTE', 'MOISIA', 'SOPHIA', 'SYLVETTE', 'ALBA', 'AMALIA', 'ANIELA', 'ANTONINA', 'CARMELA', 'CZESLAWA', 'ELISETTE', 'ERNESTA', 'ESTERINA', 'EVELYN', 'FIORINA', 'FRANCISKA', 'GIOVANINA', 'GIOVANNA', 'HENRYKA', 'JADWIGA', 'JANINA', 'JEAN-BAPTISTE', 'JOAN', 'JOSIANE', 'JULES', 'KAZMIERA', 'LEOCADIA', 'LILLIANE', 'LUCILIA', 'LUIGIA', 'MARIANNA', 'MARIE-ANGÈLE', 'MARIE-JOSÈPHE', 'MARLISE', 'MAUDE', 'NINON', 'PHILIPPA', 'POLYCARPE', 'PRIMEROSE', 'REMONDE', 'ROSARIO', 'ROSELYNE', 'SABINA', 'SATURNA', 'SUZIE', 'SYLVIANNE', 'VANDA', 'WILFRIDA', 'WLADISLAWA', 'WLADYSLAWA', 'YVA', 'ADELA', 'AIDEE', 'ALDA', 'BOZENA', 'CATALINA', 'CATERINA', 'CLELIA', 'CYRILLE', 'DAMIEN', 'DORINE', 'EDMOND', 'ELYANE', 'EMELINE', 'FANCHETTE', 'FORTUNE', 'FRANCESCA', 'GENIA', 'GODFROY', 'GUISEPPINA', 'HORTENCE', 'JANNIE', 'JANY', 'JOACHIME', 'JOSIANNE', 'JOZEFA', 'JULIANE', 'JULIANNE', 'KAZIMIRA', 'LADISLAWA', 'LEOPOLD', 'LOLITA', 'LUCIANE', 'MARIE-DENISE', 'MARIE-JOSÉ', 'MARIE-RITA', 'MARINA', 'MARTA', 'MAURILLIA', 'OLIVETTE', 'ONESIPHORE', 'ROSALIA', 'ROSANNE', 'STEFANIA', 'STEPHANIA', 'TOSCA', 'VALERIA', 'VERONIKA', 'VLASTA', 'WADYSLAWA', 'YADWIGA', 'ZOFIA', 'ADELIE', 'ALBINA', 'ALETH', 'ANNEA', 'ANNONCIAT', 'AUDETTE', 'BELLA', 'BENITA', 'BIANCA', 'BIBI', 'CESARINA', 'CESLAWA', 'CORINNE', 'DIANA', 'EDME', 'ERMIDA', 'FELISA', 'FRANCILE', 'GENOWEFA', 'GERTRUDA', 'GLORIA', 'ILONA', 'JANNINA', 'JOSELINE', 'JOSYANE', 'JOSÉ', 'JULIANNA', 'KASIMIRA', 'LILIANA', 'MARGUERITE-MARIE', 'MARION', 'MARISE', 'MARLIESE', 'MARLYSE', 'MIECZYSLAWA', 'NESTOR', 'ODYLE', 'RAYMONE', 'SAVINE', 'SEVERINA', 'STEPHANA', 'TERESA', 'VIOLANDA', 'VIRGINIA', 'YANINA', 'ZOFJA', 'AGNIELA', 'ALEXANDRE', 'ANA', 'ANDRETTE', 'ARIANE', 'AURÉLIEN', 'BARNABEE', 'BRUNETTA', 'CAROLINA', 'CHRISTINA', 'DOCTROVEE', 'DORINA', 'DÉSIRÉ', 'EDVIGE', 'FRANCESA', 'FULVIA', 'GENOVEFA', 'GIUSEPPINA', 'GIZELLE', 'GUILAINE', 'HALINA', 'HÉLÈNA', 'JACOB', 'JEANINA', 'LOETARE', 'LUDMILLA', 'MARC', 'MARCELINA', 'MARIE-ALINE', 'MARIE-CLAUDE', 'MARIE-PAULE', 'MARIUS', 'MAXIMIN', 'NORINA', 'PAQUITA', 'RAOULE', 'RIGOBERTE', 'ROSIANE', 'RUFIN', 'SILVIA', 'THEOPHILA', 'VANIA', 'AICHA', 'ALPHONSE', 'ANTONIETTA', 'ARMANDA', 'AURORA', 'BOLESLAWA', 'CONCETTA', 'CÉLESTINE', 'EDMONISE', 'ELEONORA', 'ELLIANE', 'FERDINAND', 'FRANCILLETTE', 'GRAZIA', 'HELIER', 'IOLE', 'IRIDE', 'JUSTE', 'LISIANE', 'MARIE-JEANNINE', 'MIMI', 'MYRTHA', 'OLIVIER', 'PAOLA', 'PAULMISE', 'RENELISE', 'STEFKA', 'TAMARA', 'TIMOLEON', 'VELIA', 'VITTORIA', 'ALBAN', 'AURETTE', 'CARMELIE', 'CONSUELO', 'DIDIERE', 'FANY', 'FELICIANNE', 'FILLETTE', 'FRANCEZA', 'HÉLÉNA', 'IGNACIE', 'JANNIK', 'JOSINE', 'LEONILDA', 'LILETTE', 'LUDMILA', 'MARIE-LAURE', 'MARYANNA', 'MIRALDA', 'NATHALIA', 'NINETTE', 'NOËLE', 'RAQUEL', 'ROSE-MERY', 'SANTA', 'SIMEON', 'SOFIA', 'ANICK', 'CLORINDA', 'FERNANDA', 'GODELAINE', 'LAURIANE', 'LEONCETTE', 'LINETTE', 'MEDELICE', 'NUNZIA', 'ROSELIE', 'ROSEMARY', 'SOCRATE', 'SOSTHENES', 'THEA', 'VICTORIENNE', 'AISSA', 'ALBERTINA', 'ANDRENA', 'ARMEL', 'ASTRID', 'CASIMIERA', 'DANIELA', 'ENIMIE', 'EUDES', 'GATIEN', 'GERAUD', 'GIOVANNINA', 'GITA', 'HENRIANE', 'HONORE', 'JASMINE', 'JEANINNE', 'JOËLLE', 'KRYSTYNA', 'LAMBERT', 'MARGOTTE', 'QUIRIN', 'SONJA', 'STANISE', 'STANISLAVA', 'SUZELLE', 'XENIA', 'AUBIERGE', 'CASIMIRE', 'CHANTALE', 'CRESCENTE', 'EUTROPE', 'FULBERTE', 'FÉLICIE', 'GISELA', 'GISMONDE', 'HEDVIGE', 'HENIA', 'HONORATA', 'HUGETTE', 'INCARNACION', 'JANICK', 'JANIE', 'JANYNE', 'JINETTE', 'JOSELYNE', 'MAGUY', 'MARIE-CHANTAL', 'MARIE-ODETTE', 'MARIE-PIERRE', 'MARLEINE', 'MAURE', 'MONA', 'NATALIA', 'PETRA', 'ROSE-MAY', 'ROSEMARIE', 'RÉJANE', 'SALVADORA', 'STEPHANETTE', 'SYLVAIN', 'SYMPHORIEN', 'YASMINA', 'ANIC', 'ANNINE', 'AT

In [41]:
print(lst_couleurs)

['#890f0f', '#ea4747', '#f9d1d1', '#890f0f', '#ea4747', '#f9d1d1', '#890f0f', '#ea4747', '#f9d1d1', '#890f0f', '#ea4847', '#f9d1d1', '#890f0f', '#ea4847', '#f9d1d1', '#890f0f', '#ea4847', '#f9d1d1', '#89100f', '#ea4847', '#f9d1d1', '#89100f', '#ea4847', '#f9d1d1', '#89100f', '#ea4847', '#f9d1d1', '#89100f', '#ea4947', '#f9d1d1', '#89100f', '#ea4947', '#f9d1d1', '#89100f', '#ea4947', '#f9d1d1', '#89100f', '#ea4947', '#f9d1d1', '#89110f', '#ea4947', '#f9d1d1', '#89110f', '#ea4a47', '#f9d1d1', '#89110f', '#ea4a47', '#f9d1d1', '#89110f', '#ea4a47', '#f9d1d1', '#89110f', '#ea4a47', '#f9d1d1', '#89110f', '#ea4a47', '#f9d1d1', '#89110f', '#ea4a47', '#f9d1d1', '#89120f', '#ea4b47', '#f9d2d1', '#89120f', '#ea4b47', '#f9d2d1', '#89120f', '#ea4b47', '#f9d2d1', '#89120f', '#ea4b47', '#f9d2d1', '#89120f', '#ea4b47', '#f9d2d1', '#89120f', '#ea4c47', '#f9d2d1', '#89120f', '#ea4c47', '#f9d2d1', '#89120f', '#ea4c47', '#f9d2d1', '#89130f', '#ea4c47', '#f9d2d1', '#89130f', '#ea4c47', '#f9d2d1', '#89130f', '#ea4c47', '#f9d2d1', '#89130f', '#ea4d47', '#f9d2d1', '#89130f', '#ea4d47', '#f9d2d1', '#89130f', '#ea4d47', '#f9d2d1', '#89130f', '#ea4d47', '#f9d2d1', '#89140f', '#ea4d47', '#f9d2d1', '#89140f', '#ea4e47', '#f9d2d1', '#89140f', '#ea4e47', '#f9d2d1', '#89140f', '#ea4e47', '#f9d2d1', '#89140f', '#ea4e47', '#f9d2d1', '#89140f', '#ea4e47', '#f9d2d1', '#89140f', '#ea4e47', '#f9d2d1', '#89150f', '#ea4f47', '#f9d3d1', '#89150f', '#ea4f47', '#f9d3d1', '#89150f', '#ea4f47', '#f9d3d1', '#89150f', '#ea4f47', '#f9d3d1', '#89150f', '#ea4f47', '#f9d3d1', '#89150f', '#ea5047', '#f9d3d1', '#89150f', '#ea5047', '#f9d3d1', '#89150f', '#ea5047', '#f9d3d1', '#89160f', '#ea5047', '#f9d3d1', '#89160f', '#ea5047', '#f9d3d1', '#89160f', '#ea5047', '#f9d3d1', '#89160f', '#ea5147', '#f9d3d1', '#89160f', '#ea5147', '#f9d3d1', '#89160f', '#ea5147', '#f9d3d1', '#89160f', '#ea5147', '#f9d3d1', '#89170f', '#ea5147', '#f9d3d1', '#89170f', '#ea5247', '#f9d3d1', '#89170f', '#ea5247', '#f9d3d1', '#89170f', '#ea5247', '#f9d3d1', '#89170f', '#ea5247', '#f9d3d1', '#89170f', '#ea5247', '#f9d3d1', '#89170f', '#ea5247', '#f9d3d1', '#89180f', '#ea5347', '#f9d4d1', '#89180f', '#ea5347', '#f9d4d1', '#89180f', '#ea5347', '#f9d4d1', '#89180f', '#ea5347', '#f9d4d1', '#89180f', '#ea5347', '#f9d4d1', '#89180f', '#ea5447', '#f9d4d1', '#89180f', '#ea5447', '#f9d4d1', '#89180f', '#ea5447', '#f9d4d1', '#89190f', '#ea5447', '#f9d4d1', '#89190f', '#ea5447', '#f9d4d1', '#89190f', '#ea5447', '#f9d4d1', '#89190f', '#ea5547', '#f9d4d1', '#89190f', '#ea5547', '#f9d4d1', '#89190f', '#ea5547', '#f9d4d1', '#89190f', '#ea5547', '#f9d4d1', '#891a0f', '#ea5547', '#f9d4d1', '#891a0f', '#ea5647', '#f9d4d1', '#891a0f', '#ea5647', '#f9d4d1', '#891a0f', '#ea5647', '#f9d4d1', '#891a0f', '#ea5647', '#f9d4d1', '#891a0f', '#ea5647', '#f9d4d1', '#891a0f', '#ea5647', '#f9d4d1', '#891b0f', '#ea5747', '#f9d5d1', '#891b0f', '#ea5747', '#f9d5d1', '#891b0f', '#ea5747', '#f9d5d1', '#891b0f', '#ea5747', '#f9d5d1', '#891b0f', '#ea5747', '#f9d5d1', '#891b0f', '#ea5847', '#f9d5d1', '#891b0f', '#ea5847', '#f9d5d1', '#891b0f', '#ea5847', '#f9d5d1', '#891c0f', '#ea5847', '#f9d5d1', '#891c0f', '#ea5847', '#f9d5d1', '#891c0f', '#ea5847', '#f9d5d1', '#891c0f', '#ea5947', '#f9d5d1', '#891c0f', '#ea5947', '#f9d5d1', '#891c0f', '#ea5947', '#f9d5d1', '#891c0f', '#ea5947', '#f9d5d1', '#891d0f', '#ea5947', '#f9d5d1', '#891d0f', '#ea5a47', '#f9d5d1', '#891d0f', '#ea5a47', '#f9d5d1', '#891d0f', '#ea5a47', '#f9d5d1', '#891d0f', '#ea5a47', '#f9d5d1', '#891d0f', '#ea5a47', '#f9d5d1', '#891d0f', '#ea5a47', '#f9d5d1', '#891e0f', '#ea5b47', '#f9d6d1', '#891e0f', '#ea5b47', '#f9d6d1', '#891e0f', '#ea5b47', '#f9d6d1', '#891e0f', '#ea5b47', '#f9d6d1', '#891e0f', '#ea5b47', '#f9d6d1', '#891e0f', '#ea5c47', '#f9d6d1', '#891e0f', '#ea5c47', '#f9d6d1', '#891f0f', '#ea5c47', '#f9d6d1', '#891f0f', '#ea5c47', '#f9d6d1', '#891f0f', '#ea5c47', '#f9d6d1', '#891f0f', '#ea5c47', '#f9d6d1', '#891f0f', '#ea5d47', '#f9d6d1', '#891f0f', '#ea5d47', '#f9d6d1', '#891f0f', '#ea5d47', '#f9d6d1', '#891f0f', '#ea5d47', '#f9d6d1', '#89200f', '#ea5d47', '#f9d6d1', '#89200f', '#ea5e47', '#f9d6d1', '#89200f', '#ea5e47', '#f9d6d1', '#89200f', '#ea5e47', '#f9d6d1', '#89200f', '#ea5e47', '#f9d6d1', '#89200f', '#ea5e47', '#f9d6d1', '#89200f', '#ea5e47', '#f9d7d1', '#89210f', '#ea5f47', '#f9d7d1', '#89210f', '#ea5f47', '#f9d7d1', '#89210f', '#ea5f47', '#f9d7d1', '#89210f', '#ea5f47', '#f9d7d1', '#89210f', '#ea5f47', '#f9d7d1', '#89210f', '#ea6047', '#f9d7d1', '#89210f', '#ea6047', '#f9d7d1', '#89220f', '#ea6047', '#f9d7d1', '#89220f', '#ea6047', '#f9d7d1', '#89220f', '#ea6047', '#f9d7d1', '#89220f', '#ea6047', '#f9d7d1', '#89220f', '#ea6147', '#f9d7d1', '#89220f', '#ea6147', '#f9d7d1', '#89220f', '#ea6147', '#f9d7d1', '#89220f', '#ea6147', '#f9d7d1', '#89230f', '#ea6147', '#f9d7d1', '#89230f', '#ea6247', '#f9d7d1', '#89230f', '#ea6247', '#f9d7d1', '#89230f', '#ea6247', '#f9d7d1', '#89230f', '#ea6247', '#f9d7d1', '#89230f', '#ea6247', '#f9d7d1', '#89230f', '#ea6247', '#f9d8d1', '#89240f', '#ea6347', '#f9d8d1', '#89240f', '#ea6347', '#f9d8d1', '#89240f', '#ea6347', '#f9d8d1', '#89240f', '#ea6347', '#f9d8d1', '#89240f', '#ea6347', '#f9d8d1', '#89240f', '#ea6447', '#f9d8d1', '#89240f', '#ea6447', '#f9d8d1', '#89250f', '#ea6447', '#f9d8d1', '#89250f', '#ea6447', '#f9d8d1', '#89250f', '#ea6447', '#f9d8d1', '#89250f', '#ea6447', '#f9d8d1', '#89250f', '#ea6547', '#f9d8d1', '#89250f', '#ea6547', '#f9d8d1', '#89250f', '#ea6547', '#f9d8d1', '#89250f', '#ea6547', '#f9d8d1', '#89260f', '#ea6547', '#f9d8d1', '#89260f', '#ea6647', '#f9d8d1', '#89260f', '#ea6647', '#f9d8d1', '#89260f', '#ea6647', '#f9d8d1', '#89260f', '#ea6647', '#f9d8d1', '#89260f', '#ea6647', '#f9d8d1', '#89260f', '#ea6647', '#f9d9d1', '#89270f', '#ea6747', '#f9d9d1', '#89270f', '#ea6747', '#f9d9d1', '#89270f', '#ea6747', '#f9d9d1', '#89270f', '#ea6747', '#f9d9d1', '#89270f', '#ea6747', '#f9d9d1', '#89270f', '#ea6847', '#f9d9d1', '#89270f', '#ea6847', '#f9d9d1', '#89280f', '#ea6847', '#f9d9d1', '#89280f', '#ea6847', '#f9d9d1', '#89280f', '#ea6847', '#f9d9d1', '#89280f', '#ea6847', '#f9d9d1', '#89280f', '#ea6947', '#f9d9d1', '#89280f', '#ea6947', '#f9d9d1', '#89280f', '#ea6947', '#f9d9d1', '#89280f', '#ea6947', '#f9d9d1', '#89290f', '#ea6947', '#f9d9d1', '#89290f', '#ea6a47', '#f9d9d1', '#89290f', '#ea6a47', '#f9d9d1', '#89290f', '#ea6a47', '#f9d9d1', '#89290f', '#ea6a47', '#f9d9d1', '#89290f', '#ea6a47', '#f9d9d1', '#89290f', '#ea6a47', '#f9dad1', '#892a0f', '#ea6b47', '#f9dad1', '#892a0f', '#ea6b47', '#f9dad1', '#892a0f', '#ea6b47', '#f9dad1', '#892a0f', '#ea6b47', '#f9dad1', '#892a0f', '#ea6b47', '#f9dad1', '#892a0f', '#ea6c47', '#f9dad1', '#892a0f', '#ea6c47', '#f9dad1', '#892b0f', '#ea6c47', '#f9dad1', '#892b0f', '#ea6c47', '#f9dad1', '#892b0f', '#ea6c47', '#f9dad1', '#892b0f', '#ea6c47', '#f9dad1', '#892b0f', '#ea6d47', '#f9dad1', '#892b0f', '#ea6d47', '#f9dad1', '#892b0f', '#ea6d47', '#f9dad1', '#892b0f', '#ea6d47', '#f9dad1', '#892c0f', '#ea6d47', '#f9dad1', '#892c0f', '#ea6e47', '#f9dad1', '#892c0f', '#ea6e47', '#f9dad1', '#892c0f', '#ea6e47', '#f9dad1', '#892c0f', '#ea6e47', '#f9dad1', '#892c0f', '#ea6e47', '#f9dad1', '#892c0f', '#ea6e47', '#f9dbd1', '#892d0f', '#ea6f47', '#f9dbd1', '#892d0f', '#ea6f47', '#f9dbd1', '#892d0f', '#ea6f47', '#f9dbd1', '#892d0f', '#ea6f47', '#f9dbd1', '#892d0f', '#ea6f47', '#f9dbd1', '#892d0f', '#ea7047', '#f9dbd1', '#892d0f', '#ea7047', '#f9dbd1', '#892e0f', '#ea7047', '#f9dbd1', '#892e0f', '#ea7047', '#f9dbd1', '#892e0f', '#ea7047', '#f9dbd1', '#892e0f', '#ea7047', '#f9dbd1', '#892e0f', '#ea7147', '#f9dbd1', '#892e0f', '#ea7147', '#f9dbd1', '#892e0f', '#ea7147', '#f9dbd1', '#892e0f', '#ea7147', '#f9dbd1', '#892f0f', '#ea7147', '#f9dbd1', '#892f0f', '#ea7247', '#f9dbd1', '#892f0f', '#ea7247', '#f9dbd1', '#892f0f', '#ea7247', '#f9dbd1', '#892f0f', '#ea7247', '#f9dbd1', '#892f0f', '#ea7247', '#f9dbd1', '#892f0f', '#ea7247', '#f9dcd1', '#89300f', '#ea7347', '#f9dcd1', '#89300f', '#ea7347', '#f9dcd1', '#89300f', '#ea7347', '#f9dcd1', '#89300f', '#ea7347', '#f9dcd1', '#89300f', '#ea7347', '#f9dcd1', '#89300f', '#ea7447', '#f9dcd1', '#89300f', '#ea7447', '#f9dcd1', '#89310f', '#ea7447', '#f9dcd1', '#89310f', '#ea7447', '#f9dcd1', '#89310f', '#ea7447', '#f9dcd1', '#89310f', '#ea7447', '#f9dcd1', '#89310f', '#ea7547', '#f9dcd1', '#89310f', '#ea7547', '#f9dcd1', '#89310f', '#ea7547', '#f9dcd1', '#89310f', '#ea7547', '#f9dcd1', '#89320f', '#ea7547', '#f9dcd1', '#89320f', '#ea7647', '#f9dcd1', '#89320f', '#ea7647', '#f9dcd1', '#89320f', '#ea7647', '#f9dcd1', '#89320f', '#ea7647', '#f9dcd1', '#89320f', '#ea7647', '#f9dcd1', '#89320f', '#ea7647', '#f9ddd1', '#89330f', '#ea7747', '#f9ddd1', '#89330f', '#ea7747', '#f9ddd1', '#89330f', '#ea7747', '#f9ddd1', '#89330f', '#ea7747', '#f9ddd1', '#89330f', '#ea7747', '#f9ddd1', '#89330f', '#ea7847', '#f9ddd1', '#89330f', '#ea7847', '#f9ddd1', '#89340f', '#ea7847', '#f9ddd1', '#89340f', '#ea7847', '#f9ddd1', '#89340f', '#ea7847', '#f9ddd1', '#89340f', '#ea7847', '#f9ddd1', '#89340f', '#ea7947', '#f9ddd1', '#89340f', '#ea7947', '#f9ddd1', '#89340f', '#ea7947', '#f9ddd1', '#89340f', '#ea7947', '#f9ddd1', '#89350f', '#ea7947', '#f9ddd1', '#89350f', '#ea7a47', '#f9ddd1', '#89350f', '#ea7a47', '#f9ddd1', '#89350f', '#ea7a47', '#f9ddd1', '#89350f', '#ea7a47', '#f9ddd1', '#89350f', '#ea7a47', '#f9ddd1', '#89350f', '#ea7a47', '#f9ded1', '#89360f', '#ea7b47', '#f9ded1', '#89360f', '#ea7b47', '#f9ded1', '#89360f', '#ea7b47', '#f9ded1', '#89360f', '#ea7b47', '#f9ded1', '#89360f', '#ea7b47', '#f9ded1', '#89360f', '#ea7c47', '#f9ded1', '#89360f', '#ea7c47', '#f9ded1', '#89370f', '#ea7c47', '#f9ded1', '#89370f', '#ea7c47', '#f9ded1', '#89370f', '#ea7c47', '#f9ded1', '#89370f', '#ea7c47', '#f9ded1', '#89370f', '#ea7d47', '#f9ded1', '#89370f', '#ea7d47', '#f9ded1', '#89370f', '#ea7d47', '#f9ded1', '#89370f', '#ea7d47', '#f9ded1', '#89380f', '#ea7d47', '#f9ded1', '#89380f', '#ea7e47', '#f9ded1', '#89380f', '#ea7e47', '#f9ded1', '#89380f', '#ea7e47', '#f9ded1', '#89380f', '#ea7e47', '#f9ded1', '#89380f', '#ea7e47', '#f9ded1', '#89380f', '#ea7e47', '#f9dfd1', '#89390f', '#ea7f47', '#f9dfd1', '#89390f', '#ea7f47', '#f9dfd1', '#89390f', '#ea7f47', '#f9dfd1', '#89390f', '#ea7f47', '#f9dfd1', '#89390f', '#ea7f47', '#f9dfd1', '#89390f', '#ea8047', '#f9dfd1', '#89390f', '#ea8047', '#f9dfd1', '#893a0f', '#ea8047', '#f9dfd1', '#893a0f', '#ea8047', '#f9dfd1', '#893a0f', '#ea8047', '#f9dfd1', '#893a0f', '#ea8047', '#f9dfd1', '#893a0f', '#ea8147', '#f9dfd1', '#893a0f', '#ea8147', '#f9dfd1', '#893a0f', '#ea8147', '#f9dfd1', '#893a0f', '#ea8147', '#f9dfd1', '#893b0f', '#ea8147', '#f9dfd1', '#893b0f', '#ea8247', '#f9dfd1', '#893b0f', '#ea8247', '#f9dfd1', '#893b0f', '#ea8247', '#f9dfd1', '#893b0f', '#ea8247', '#f9dfd1', '#893b0f', '#ea8247', '#f9dfd1', '#893b0f', '#ea8247', '#f9e0d1', '#893c0f', '#ea8347', '#f9e0d1', '#893c0f', '#ea8347', '#f9e0d1', '#893c0f', '#ea8347', '#f9e0d1', '#893c0f', '#ea8347', '#f9e0d1', '#893c0f', '#ea8347', '#f9e0d1', '#893c0f', '#ea8447', '#f9e0d1', '#893c0f', '#ea8447', '#f9e0d1', '#893d0f', '#ea8447', '#f9e0d1', '#893d0f', '#ea8447', '#f9e0d1', '#893d0f', '#ea8447', '#f9e0d1', '#893d0f', '#ea8447', '#f9e0d1', '#893d0f', '#ea8547', '#f9e0d1', '#893d0f', '#ea8547', '#f9e0d1', '#893d0f', '#ea8547', '#f9e0d1', '#893d0f', '#ea8547', '#f9e0d1', '#893e0f', '#ea8547', '#f9e0d1', '#893e0f', '#ea8647', '#f9e0d1', '#893e0f', '#ea8647', '#f9e0d1', '#893e0f', '#ea8647', '#f9e0d1', '#893e0f', '#ea8647', '#f9e0d1', '#893e0f', '#ea8647', '#f9e0d1', '#893e0f', '#ea8647', '#f9e1d1', '#893f0f', '#ea8747', '#f9e1d1', '#893f0f', '#ea8747', '#f9e1d1', '#893f0f', '#ea8747', '#f9e1d1', '#893f0f', '#ea8747', '#f9e1d1', '#893f0f', '#ea8747', '#f9e1d1', '#893f0f', '#ea8847', '#f9e1d1', '#893f0f', '#ea8847', '#f9e1d1', '#89400f', '#ea8847', '#f9e1d1', '#89400f', '#ea8847', '#f9e1d1', '#89400f', '#ea8847', '#f9e1d1', '#89400f', '#ea8847', '#f9e1d1', '#89400f', '#ea8947', '#f9e1d1', '#89400f', '#ea8947', '#f9e1d1', '#89400f', '#ea8947', '#f9e1d1', '#89400f', '#ea8947', '#f9e1d1', '#89410f', '#ea8947', '#f9e1d1', '#89410f', '#ea8a47', '#f9e1d1', '#89410f', '#ea8a47', '#f9e1d1', '#89410f', '#ea8a47', '#f9e1d1', '#89410f', '#ea8a47', '#f9e1d1', '#89410f', '#ea8a47', '#f9e1d1', '#89410f', '#ea8a47', '#f9e2d1', '#89420f', '#ea8b47', '#f9e2d1', '#89420f', '#ea8b47', '#f9e2d1', '#89420f', '#ea8b47', '#f9e2d1', '#89420f', '#ea8b47', '#f9e2d1', '#89420f', '#ea8b47', '#f9e2d1', '#89420f', '#ea8c47', '#f9e2d1', '#89420f', '#ea8c47', '#f9e2d1', '#89430f', '#ea8c47', '#f9e2d1', '#89430f', '#ea8c47', '#f9e2d1', '#89430f', '#ea8c47', '#f9e2d1', '#89430f', '#ea8c47', '#f9e2d1', '#89430f', '#ea8d47', '#f9e2d1', '#89430f', '#ea8d47', '#f9e2d1', '#89430f', '#ea8d47', '#f9e2d1', '#89430f', '#ea8d47', '#f9e2d1', '#89440f', '#ea8d47', '#f9e2d1', '#89440f', '#ea8e47', '#f9e2d1', '#89440f', '#ea8e47', '#f9e2d1', '#89440f', '#ea8e47', '#f9e2d1', '#89440f', '#ea8e47', '#f9e2d1', '#89440f', '#ea8e47', '#f9e2d1', '#89440f', '#ea8e47', '#f9e3d1', '#89450f', '#ea8f47', '#f9e3d1', '#89450f', '#ea8f47', '#f9e3d1', '#89450f', '#ea8f47', '#f9e3d1', '#89450f', '#ea8f47', '#f9e3d1', '#89450f', '#ea8f47', '#f9e3d1', '#89450f', '#ea9047', '#f9e3d1', '#89450f', '#ea9047', '#f9e3d1', '#89460f', '#ea9047', '#f9e3d1', '#89460f', '#ea9047', '#f9e3d1', '#89460f', '#ea9047', '#f9e3d1', '#89460f', '#ea9147', '#f9e3d1', '#89460f', '#ea9147', '#f9e3d1', '#89460f', '#ea9147', '#f9e3d1', '#89460f', '#ea9147', '#f9e3d1', '#89470f', '#ea9147', '#f9e3d1', '#89470f', '#ea9147', '#f9e3d1', '#89470f', '#ea9247', '#f9e3d1', '#89470f', '#ea9247', '#f9e3d1', '#89470f', '#ea9247', '#f9e3d1', '#89470f', '#ea9247', '#f9e3d1', '#89470f', '#ea9247', '#f9e3d1', '#89470f', '#ea9347', '#f9e4d1', '#89480f', '#ea9347', '#f9e4d1', '#89480f', '#ea9347', '#f9e4d1', '#89480f', '#ea9347', '#f9e4d1', '#89480f', '#ea9347', '#f9e4d1', '#89480f', '#ea9347', '#f9e4d1', '#89480f', '#ea9447', '#f9e4d1', '#89480f', '#ea9447', '#f9e4d1', '#89490f', '#ea9447', '#f9e4d1', '#89490f', '#ea9447', '#f9e4d1', '#89490f', '#ea9447', '#f9e4d1', '#89490f', '#ea9547', '#f9e4d1', '#89490f', '#ea9547', '#f9e4d1', '#89490f', '#ea9547', '#f9e4d1', '#89490f', '#ea9547', '#f9e4d1', '#894a0f', '#ea9547', '#f9e4d1', '#894a0f', '#ea9547', '#f9e4d1', '#894a0f', '#ea9647', '#f9e4d1', '#894a0f', '#ea9647', '#f9e4d1', '#894a0f', '#ea9647', '#f9e4d1', '#894a0f', '#ea9647', '#f9e4d1', '#894a0f', '#ea9647', '#f9e4d1', '#894a0f', '#ea9747', '#f9e5d1', '#894b0f', '#ea9747', '#f9e5d1', '#894b0f', '#ea9747', '#f9e5d1', '#894b0f', '#ea9747', '#f9e5d1', '#894b0f', '#ea9747', '#f9e5d1', '#894b0f', '#ea9747', '#f9e5d1', '#894b0f', '#ea9847', '#f9e5d1', '#894b0f', '#ea9847', '#f9e5d1', '#894c0f', '#ea9847', '#f9e5d1', '#894c0f', '#ea9847', '#f9e5d1', '#894c0f', '#ea9847', '#f9e5d1', '#894c0f', '#ea9947', '#f9e5d1', '#894c0f', '#ea9947', '#f9e5d1', '#894c0f', '#ea9947', '#f9e5d1', '#894c0f', '#ea9947', '#f9e5d1', '#894d0f', '#ea9947', '#f9e5d1', '#894d0f', '#ea9947', '#f9e5d1', '#894d0f', '#ea9a47', '#f9e5d1', '#894d0f', '#ea9a47', '#f9e5d1', '#894d0f', '#ea9a47', '#f9e5d1', '#894d0f', '#ea9a47', '#f9e5d1', '#894d0f', '#ea9a47', '#f9e5d1', '#894d0f', '#ea9b47', '#f9e6d1', '#894e0f', '#ea9b47', '#f9e6d1', '#894e0f', '#ea9b47', '#f9e6d1', '#894e0f', '#ea9b47', '#f9e6d1', '#894e0f', '#ea9b47', '#f9e6d1', '#894e0f', '#ea9b47', '#f9e6d1', '#894e0f', '#ea9c47', '#f9e6d1', '#894e0f', '#ea9c47', '#f9e6d1', '#894f0f', '#ea9c47', '#f9e6d1', '#894f0f', '#ea9c47', '#f9e6d1', '#894f0f', '#ea9c47', '#f9e6d1', '#894f0f', '#ea9d47', '#f9e6d1', '#894f0f', '#ea9d47', '#f9e6d1', '#894f0f', '#ea9d47', '#f9e6d1', '#894f0f', '#ea9d47', '#f9e6d1', '#89500f', '#ea9d47', '#f9e6d1', '#89500f', '#ea9d47', '#f9e6d1', '#89500f', '#ea9e47', '#f9e6d1', '#89500f', '#ea9e47', '#f9e6d1', '#89500f', '#ea9e47', '#f9e6d1', '#89500f', '#ea9e47', '#f9e6d1', '#89500f', '#ea9e47', '#f9e6d1', '#89500f', '#ea9f47', '#f9e7d1', '#89510f', '#ea9f47', '#f9e7d1', '#89510f', '#ea9f47', '#f9e7d1', '#89510f', '#ea9f47', '#f9e7d1', '#89510f', '#ea9f47', '#f9e7d1', '#89510f', '#ea9f47', '#f9e7d1', '#89510f', '#eaa047', '#f9e7d1', '#89510f', '#eaa047', '#f9e7d1', '#89520f', '#eaa047', '#f9e7d1', '#89520f', '#eaa047', '#f9e7d1', '#89520f', '#eaa047', '#f9e7d1', '#89520f', '#eaa147', '#f9e7d1', '#89520f', '#eaa147', '#f9e7d1', '#89520f', '#eaa147', '#f9e7d1', '#89520f', '#eaa147', '#f9e7d1', '#89530f', '#eaa147', '#f9e7d1', '#89530f', '#eaa147', '#f9e7d1', '#89530f', '#eaa247', '#f9e7d1', '#89530f', '#eaa247', '#f9e7d1', '#89530f', '#eaa247', '#f9e7d1', '#89530f', '#eaa247', '#f9e7d1', '#89530f', '#eaa247', '#f9e7d1', '#89530f', '#eaa347', '#f9e8d1', '#89540f', '#eaa347', '#f9e8d1', '#89540f', '#eaa347', '#f9e8d1', '#89540f', '#eaa347', '#f9e8d1', '#89540f', '#eaa347', '#f9e8d1', '#89540f', '#eaa347', '#f9e8d1', '#89540f', '#eaa447', '#f9e8d1', '#89540f', '#eaa447', '#f9e8d1', '#89550f', '#eaa447', '#f9e8d1', '#89550f', '#eaa447', '#f9e8d1', '#89550f', '#eaa447', '#f9e8d1', '#89550f', '#eaa547', '#f9e8d1', '#89550f', '#eaa547', '#f9e8d1', '#89550f', '#eaa547', '#f9e8d1', '#89550f', '#eaa547', '#f9e8d1', '#89560f', '#eaa547', '#f9e8d1', '#89560f', '#eaa547', '#f9e8d1', '#89560f', '#eaa647', '#f9e8d1', '#89560f', '#eaa647', '#f9e8d1', '#89560f', '#eaa647', '#f9e8d1', '#89560f', '#eaa647', '#f9e8d1', '#89560f', '#eaa647', '#f9e8d1', '#89560f', '#eaa747', '#f9e9d1', '#89570f', '#eaa747', '#f9e9d1', '#89570f', '#eaa747', '#f9e9d1', '#89570f', '#eaa747', '#f9e9d1', '#89570f', '#eaa747', '#f9e9d1', '#89570f', '#eaa747', '#f9e9d1', '#89570f', '#eaa847', '#f9e9d1', '#89570f', '#eaa847', '#f9e9d1', '#89580f', '#eaa847', '#f9e9d1', '#89580f', '#eaa847', '#f9e9d1', '#89580f', '#eaa847', '#f9e9d1', '#89580f', '#eaa947', '#f9e9d1', '#89580f', '#eaa947', '#f9e9d1', '#89580f', '#eaa947', '#f9e9d1', '#89580f', '#eaa947', '#f9e9d1', '#89590f', '#eaa947', '#f9e9d1', '#89590f', '#eaa947', '#f9e9d1', '#89590f', '#eaaa47', '#f9e9d1', '#89590f', '#eaaa47', '#f9e9d1', '#89590f', '#eaaa47', '#f9e9d1', '#89590f', '#eaaa47', '#f9e9d1', '#89590f', '#eaaa47', '#f9e9d1', '#89590f', '#eaab47', '#f9ead1', '#895a0f', '#eaab47', '#f9ead1', '#895a0f', '#eaab47', '#f9ead1', '#895a0f', '#eaab47', '#f9ead1', '#895a0f', '#eaab47', '#f9ead1', '#895a0f', '#eaab47', '#f9ead1', '#895a0f', '#eaac47', '#f9ead1', '#895a0f', '#eaac47', '#f9ead1', '#895b0f', '#eaac47', '#f9ead1', '#895b0f', '#eaac47', '#f9ead1', '#895b0f', '#eaac47', '#f9ead1', '#895b0f', '#eaad47', '#f9ead1', '#895b0f', '#eaad47', '#f9ead1', '#895b0f', '#eaad47', '#f9ead1', '#895b0f', '#eaad47', '#f9ead1', '#895c0f', '#eaad47', '#f9ead1', '#895c0f', '#eaad47', '#f9ead1', '#895c0f', '#eaae47', '#f9ead1', '#895c0f', '#eaae47', '#f9ead1', '#895c0f', '#eaae47', '#f9ead1', '#895c0f', '#eaae47', '#f9ead1', '#895c0f', '#eaae47', '#f9ead1', '#895c0f', '#eaaf47', '#f9ebd1', '#895d0f', '#eaaf47', '#f9ebd1', '#895d0f', '#eaaf47', '#f9ebd1', '#895d0f', '#eaaf47', '#f9ebd1', '#895d0f', '#eaaf47', '#f9ebd1', '#895d0f', '#eaaf47', '#f9ebd1', '#895d0f', '#eab047', '#f9ebd1', '#895d0f', '#eab047', '#f9ebd1', '#895e0f', '#eab047', '#f9ebd1', '#895e0f', '#eab047', '#f9ebd1', '#895e0f', '#eab047', '#f9ebd1', '#895e0f', '#eab147', '#f9ebd1', '#895e0f', '#eab147', '#f9ebd1', '#895e0f', '#eab147', '#f9ebd1', '#895e0f', '#eab147', '#f9ebd1', '#895f0f', '#eab147', '#f9ebd1', '#895f0f', '#eab147', '#f9ebd1', '#895f0f', '#eab247', '#f9ebd1', '#895f0f', '#eab247', '#f9ebd1', '#895f0f', '#eab247', '#f9ebd1', '#895f0f', '#eab247', '#f9ebd1', '#895f0f', '#eab247', '#f9ebd1', '#895f0f', '#eab347', '#f9ecd1', '#89600f', '#eab347', '#f9ecd1', '#89600f', '#eab347', '#f9ecd1', '#89600f', '#eab347', '#f9ecd1', '#89600f', '#eab347', '#f9ecd1', '#89600f', '#eab347', '#f9ecd1', '#89600f', '#eab447', '#f9ecd1', '#89600f', '#eab447', '#f9ecd1', '#89610f', '#eab447', '#f9ecd1', '#89610f', '#eab447', '#f9ecd1', '#89610f', '#eab447', '#f9ecd1', '#89610f', '#eab547', '#f9ecd1', '#89610f', '#eab547', '#f9ecd1', '#89610f', '#eab547', '#f9ecd1', '#89610f', '#eab547', '#f9ecd1', '

   annais    preusuel  sexe  nombre  annees
0    1900        ABEL     1     382    1900
1    1900     ABRAHAM     1       9    1900
2    1900     ACHILLE     1     152    1900
3    1900    ACHILLES     1       4    1900
4    1900        ADAM     1       9    1900
..    ...         ...   ...     ...     ...
95   1900        ANNE     2    3440    1900
96   1900  ANNE-MARIE     2      62    1900
97   1900       ANNET     1      17    1900
98   1900     ANNETTE     2     181    1900
99   1900      ANNITA     2       3    1900

[100 rows x 5 columns]

In [144]:
names_colores = ajouter_couleurs_etendues(names)

In [46]:
import colorsys

def generer_couleurs_eloignees(n, clarte=0.5, saturation=0.8):
    """
    Génère n couleurs spectralement distantes.
    
    :param n: Nombre de couleurs souhaitées.
    :param clarte: Une valeur unique (ex: 0.5) ou une liste/tuple de valeurs (ex: [0.4, 0.7]) 
                   pour faire varier la luminosité.
    :param saturation: Saturation des couleurs (entre 0.0 et 1.0).
    :return: Liste de codes couleur Hexadécimaux.
    """
    couleurs = []
    
    for i in range(n):
        # Division égale du cercle chromatique (Teinte entre 0.0 et 1.0)
        teinte = i / n
        
        # Gestion de la clarté (fixe ou alternée)
        if isinstance(clarte, (list, tuple)):
            c = clarte[i % len(clarte)]  # Alterne entre les clartés fournies
        else:
            c = clarte
            
        # Conversion HSL (HLS en Python) vers RGB (valeurs entre 0.0 et 1.0)
        r, g, b = colorsys.hls_to_rgb(teinte, c, saturation)
        
        # Conversion en format Hexadécimal (#RRGGBB)
        hex_color = f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"
        couleurs.append(hex_color)
        
    return couleurs

In [48]:
ma_palette = generer_couleurs_eloignees(n=6, clarte=[0.4, 0.65], saturation=0.85)

In [56]:
slider = alt.binding_range(min=1900, max=2020, step=1, name='year:')
year = alt.param(value=2004, bind=slider)
selection = alt.selection_point(fields=["annees"], bind=slider)

base = alt.Chart(names_colores).mark_bar().encode(
    x = 'nombre:Q',
    y =alt.Y('preusuel:N', sort='-x'),
# color=alt.Color('couleur:N').scale(
#     domain=names_colores['couleur'].unique().tolist(), 
#     range=names_colores['couleur'].unique().tolist()
# ).legend(None)

color=alt.Color(
        'preusuel:N', 
        scale=alt.Scale(range=ma_palette) # On applique notre palette ici
    )
    
).add_params(
    year
).transform_filter(
    alt.datum.annais == alt.expr.toString(year),
).transform_window(    
    rank ='rank(nombre)',
    sort=[alt.SortField('nombre', order='descending')]
).transform_filter(
    alt.datum.rank <=20
).properties(
    width=600,
    height=400
)

In [57]:
base

alt.Chart(...)

In [127]:
import colorsys

def generer_couleurs_par_groupe(n, hue_start, hue_end, clarte=[0.2, 0.4, 0.6, 0.8], saturation=0.8):
    """Génère n couleurs distantes limitées à une plage du cercle chromatique (0.0 à 1.0)."""
    couleurs = []
    if n == 0:
        return couleurs
        
    for i in range(n):
        # Répartition des teintes uniquement entre hue_start et hue_end
        if n == 1:
            teinte = (hue_start + hue_end) / 2
        else:
            teinte = hue_start + (i / (n - 1)) * (hue_end - hue_start)
        
        # Variation de la clarté
        c = clarte[i % len(clarte)] if isinstance(clarte, (list, tuple)) else clarte
        
        # Conversion Hexadécimale
        r, g, b = colorsys.hls_to_rgb(teinte, c, saturation)
        hex_color = f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"
        couleurs.append(hex_color)
        
    return couleurs

In [128]:
# import altair as alt
# import pandas as pd

# --- 1. Données d'exemple (avec un prénom mixte "Camille") ---
# data = pd.DataFrame({
#     'Prenom': ['Alice', 'Emma', 'Camille', 'Bob', 'Charlie', 'Camille'],
#     'Sexe': ['F', 'F', 'F', 'H', 'H', 'H'],
#     'Score': [20, 14, 18, 25, 17, 12]
# })

def add_couleur_df(data) : 
# Étape cruciale : On crée une colonne d'identification unique pour la couleur
    data['Id_Couleur'] = data['preusuel'] + " (" + data['sexe'].astype(str) + ")"

    # --- 2. Génération des palettes distinctes par Sexe ---
    # On extrait les identifiants uniques triés par genre
    identifiants_filles = sorted(data[data['sexe'] == 2]['Id_Couleur'].unique())
    identifiants_garcons = sorted(data[data['sexe'] == 1]['Id_Couleur'].unique())
    print(identifiants_filles)

    # Filles : Teintes chaudes (du Violet/Rose au Rouge -> 0.75 à 0.98)
    couleurs_filles = generer_couleurs_par_groupe(len(identifiants_filles), 0.5, 0.99)
    print(couleurs_filles)

    # Garçons : Teintes froides (du Vert au Bleu/Cyan -> 0.35 à 0.68)
    couleurs_garcons = generer_couleurs_par_groupe(len(identifiants_garcons), 0.035, 0.68)

    # --- 3. Création du dictionnaire de correspondance global ---
    mapping_couleurs = {}
    mapping_couleurs.update(zip(identifiants_filles, couleurs_filles))
    print(mapping_couleurs)
    mapping_couleurs.update(zip(identifiants_garcons, couleurs_garcons))

    return mapping_couleurs

In [146]:
mapping_couleurs = add_couleur_df(names)

['AALIYA (2)', 'AALIYAH (2)', 'AALYA (2)', 'AALYAH (2)', 'ABBIE (2)', 'ABBY (2)', 'ABBY-GAËLLE (2)', 'ABBYGAELLE (2)', 'ABBYGAËLLE (2)', 'ABDON (2)', 'ABDONIE (2)', 'ABDONISE (2)', 'ABEL (2)', 'ABELIA (2)', 'ABELINE (2)', 'ABELLA (2)', 'ABELLE (2)', 'ABI (2)', 'ABIBA (2)', 'ABIBATA (2)', 'ABIGAEL (2)', 'ABIGAELLE (2)', 'ABIGAIL (2)', 'ABIGAËL (2)', 'ABIGAËLLE (2)', 'ABIGAÏL (2)', 'ABINAYA (2)', 'ABIR (2)', 'ABIRA (2)', 'ABISHA (2)', 'ABLA (2)', 'ABRAR (2)', 'ABRIL (2)', 'ABSA (2)', 'ABY (2)', 'ABYGAEL (2)', 'ABYGAELLE (2)', 'ABYGAËL (2)', 'ABYGAËLLE (2)', 'ACACIA (2)', 'ACELYA (2)', 'ACHILLE (2)', 'ACIA (2)', 'ACIL (2)', 'ADA (2)', 'ADALINE (2)', 'ADAM (2)', 'ADAMA (2)', 'ADAME (2)', 'ADDA (2)', 'ADDISON (2)', 'ADELA (2)', 'ADELAIDE (2)', 'ADELAÏDE (2)', 'ADELE (2)', 'ADELHEID (2)', 'ADELIA (2)', 'ADELIE (2)', 'ADELINA (2)', 'ADELINE (2)', 'ADELPHINE (2)', 'ADELYA (2)', 'ADELYNE (2)', 'ADIA (2)', 'ADINA (2)', 'ADINE (2)', 'ADIXIA (2)', 'ADIZA (2)', 'ADJA (2)', 'ADJARATOU (2)', 'ADJIA (2)', 'ADJILA (2)', 'ADLINE (2)', 'ADNA (2)', 'ADOLIE (2)', 'ADOLPHE (2)', 'ADOLPHINE (2)', 'ADONAI (2)', 'ADONAY (2)', 'ADRIANA (2)', 'ADRIANE (2)', 'ADRIANNA (2)', 'ADRIANNE (2)', 'ADRIEN (2)', 'ADRIENNE (2)', 'ADÈLE (2)', 'ADÉLAÏDE (2)', 'ADÉLIA (2)', 'ADÉLIE (2)', 'AEL (2)', 'AELA (2)', 'AELIA (2)', 'AELIG (2)', 'AELIS (2)', 'AELLE (2)', 'AELYS (2)', 'AENOR (2)', 'AERIS (2)', 'AERITH (2)', 'AERYN (2)', 'AFAF (2)', 'AFEF (2)', 'AFFOU (2)', 'AFIA (2)', 'AFIDA (2)', 'AFIFA (2)', 'AFNANE (2)', 'AFSANA (2)', 'AGATA (2)', 'AGATE (2)', 'AGATHA (2)', 'AGATHE (2)', 'AGLAE (2)', 'AGLAEE (2)', 'AGLAÉ (2)', 'AGNAN (2)', 'AGNES (2)', 'AGNESE (2)', 'AGNIELA (2)', 'AGNÈS (2)', 'AGUSTINA (2)', 'AH (2)', 'AHANA (2)', 'AHAVA (2)', 'AHED (2)', 'AHLAM (2)', 'AHLAME (2)', 'AHLEM (2)', 'AHLEME (2)', 'AHSEN (2)', 'AI (2)', 'AICHA (2)', 'AICHAT (2)', 'AICHATA (2)', 'AICHATOU (2)', 'AICHE (2)', 'AIDA (2)', 'AIDEE (2)', 'AIKO (2)', 'AILEEN (2)', 'AILYS (2)', 'AIMA (2)', 'AIMEE (2)', 'AIMIE (2)', 'AIMMEE (2)', 'AIMY (2)', 'AIMÉE (2)', 'AINA (2)', 'AINARA (2)', 'AINES (2)', 'AINHOA (2)', 'AINOA (2)', 'AINTZANE (2)', 'AISHA (2)', 'AISSA (2)', 'AISSATA (2)', 'AISSATOU (2)', 'AISSE (2)', 'AISSETA (2)', 'AISSETOU (2)', 'AIYA (2)', 'AIYANA (2)', 'AIZA (2)', 'AJLA (2)', 'AKILA (2)', 'AKIMA (2)', 'AKSHA (2)', 'AKSHANA (2)', 'AKSHARA (2)', 'AKSHAYA (2)', 'ALAA (2)', 'ALAE (2)', 'ALAIA (2)', 'ALAIN (2)', 'ALAIS (2)', 'ALAITZ (2)', 'ALANA (2)', 'ALANIS (2)', 'ALANNAH (2)', 'ALAYA (2)', 'ALAYNA (2)', 'ALAÏA (2)', 'ALAÏS (2)', 'ALBA (2)', 'ALBAN (2)', 'ALBANE (2)', 'ALBANIE (2)', 'ALBERT (2)', 'ALBERTA (2)', 'ALBERTE (2)', 'ALBERTINA (2)', 'ALBERTINE (2)', 'ALBINA (2)', 'ALBINE (2)', 'ALCIDA (2)', 'ALCIDIE (2)', 'ALDA (2)', 'ALDEGONDE (2)', 'ALDINA (2)', 'ALDJIA (2)', 'ALEA (2)', 'ALEENA (2)', 'ALEEYAH (2)', 'ALEKSANDRA (2)', 'ALENA (2)', 'ALESIA (2)', 'ALESSA (2)', 'ALESSANDRA (2)', 'ALESSIA (2)', 'ALESSYA (2)', 'ALETH (2)', 'ALEV (2)', 'ALEX (2)', 'ALEXA (2)', 'ALEXANDRA (2)', 'ALEXANDRE (2)', 'ALEXANDRIE (2)', 'ALEXANDRINA (2)', 'ALEXANDRINE (2)', 'ALEXANE (2)', 'ALEXANNE (2)', 'ALEXE (2)', 'ALEXIA (2)', 'ALEXIANE (2)', 'ALEXIE (2)', 'ALEXINA (2)', 'ALEXINE (2)', 'ALEXIS (2)', 'ALEXY (2)', 'ALEYA (2)', 'ALEYNA (2)', 'ALFRED (2)', 'ALFREDA (2)', 'ALFREDE (2)', 'ALFREDINE (2)', 'ALFRÉDA (2)', 'ALIA (2)', 'ALIAH (2)', 'ALIANA (2)', 'ALICE (2)', 'ALICIA (2)', 'ALICJA (2)', 'ALICYA (2)', 'ALIDA (2)', 'ALIENOR (2)', 'ALIETTE (2)', 'ALIMA (2)', 'ALIMATA (2)', 'ALIMATOU (2)', 'ALINA (2)', 'ALINE (2)', 'ALISA (2)', 'ALISE (2)', 'ALISEA (2)', 'ALISEE (2)', 'ALISHA (2)', 'ALISON (2)', 'ALISONE (2)', 'ALISSA (2)', 'ALISSIA (2)', 'ALISSON (2)', 'ALISSYA (2)', 'ALISÉE (2)', 'ALIX (2)', 'ALIXE (2)', 'ALIXIA (2)', 'ALIYA (2)', 'ALIYAH (2)', 'ALIZA (2)', 'ALIZE (2)', 'ALIZEA (2)', 'ALIZEE (2)', 'ALIZÉ (2)', 'ALIZÉA (2)', 'ALIZÉE (2)', 'ALIÉNOR (2)', 'ALLEGRA (2)', 'ALLIA (2)', 'ALLIETTE (2)', 'ALLISON (2)', 'ALLISSIA (2)', 'ALLISSON (2)', 'ALLIYA (2)', 'ALLIYAH (2)', 'ALLY (2)', 'ALLYA (2)', 'ALLYAH (2)', 'ALLYSON (2)', 'ALLYSSIA (2)', 'ALMA (2)', 'ALMAS (2)', 'ALMILA (2)', 'ALMINA (2)', 'ALMIRA (2)', 'ALODIE (2)', 'ALOISE (2)', 'ALONA (2)', 'ALOYSE (2)', 'ALOÏSE (2)', 'ALPHENA (2)', 'ALPHONSE (2)', 'ALPHONSIA (2)', 'ALPHONSINE (2)', 'ALSACE (2)', 'ALTHEA (2)', 'ALTHÉA (2)', 'ALVA (2)', 'ALVINA (2)', 'ALVINE (2)', 'ALWENA (2)', 'ALWENN (2)', 'ALWENNA (2)', 'ALWINE (2)', 'ALYA (2)', 'ALYAH (2)', 'ALYANA (2)', 'ALYANNA (2)', 'ALYCE (2)', 'ALYCIA (2)', 'ALYETTE (2)', 'ALYMA (2)', 'ALYNA (2)', 'ALYNE (2)', 'ALYS (2)', 'ALYSEE (2)', 'ALYSHA (2)', 'ALYSON (2)', 'ALYSONE (2)', 'ALYSSA (2)', 'ALYSSIA (2)', 'ALYSSON (2)', 'ALYX (2)', 'ALYXE (2)', 'ALYZEE (2)', 'ALYZÉA (2)', 'ALYZÉE (2)', 'ALZINA (2)', 'ALZIRA (2)', 'ALZIRE (2)', 'ALÉNA (2)', 'ALÉSSIA (2)', 'AMAELLE (2)', 'AMAIA (2)', 'AMAL (2)', 'AMALE (2)', 'AMALIA (2)', 'AMALIE (2)', 'AMALYA (2)', 'AMANA (2)', 'AMANCE (2)', 'AMANDA (2)', 'AMANDE (2)', 'AMANDINE (2)', 'AMANE (2)', 'AMANI (2)', 'AMANIE (2)', 'AMANTE (2)', 'AMANTHE (2)', 'AMANTINE (2)', 'AMANY (2)', 'AMARA (2)', 'AMARIA (2)', 'AMARINE (2)', 'AMARYLLIS (2)', 'AMAYA (2)', 'AMAÏA (2)', 'AMBER (2)', 'AMBRE (2)', 'AMBRINE (2)', 'AMBROISE (2)', 'AMBROISINE (2)', 'AMEDEE (2)', 'AMEDINE (2)', 'AMEENA (2)', 'AMEL (2)', 'AMELA (2)', 'AMELE (2)', 'AMELIA (2)', 'AMELIE (2)', 'AMELINA (2)', 'AMELINE (2)', 'AMELLE (2)', 'AMELY (2)', 'AMELYA (2)', 'AMELYNE (2)', 'AMEN (2)', 'AMENA (2)', 'AMENI (2)', 'AMI (2)', 'AMICIE (2)', 'AMINA (2)', 'AMINAH (2)', 'AMINAT (2)', 'AMINATA (2)', 'AMINATOU (2)', 'AMINE (2)', 'AMIRA (2)', 'AMNA (2)', 'AMOUR (2)', 'AMPARO (2)', 'AMY (2)', 'AMYNA (2)', 'AMÉLIA (2)', 'AMÉLIE (2)', 'AMÉLINE (2)', 'AMÉLY (2)', 'AMÉLYA (2)', 'ANA (2)', 'ANA-BELA (2)', 'ANA-CRISTINA (2)', 'ANA-MARIA (2)', 'ANA-PAULA (2)', 'ANABEL (2)', 'ANABELA (2)', 'ANABELLA (2)', 'ANABELLE (2)', 'ANABIA (2)', 'ANAE (2)', 'ANAEE (2)', 'ANAEL (2)', 'ANAELE (2)', 'ANAELLE (2)', 'ANAHIDE (2)', 'ANAHIT (2)', 'ANAHITA (2)', 'ANAHÉ (2)', 'ANAIA (2)', 'ANAICK (2)', 'ANAIG (2)', 'ANAIK (2)', 'ANAIS (2)', 'ANAISE (2)', 'ANAIZ (2)', 'ANALIA (2)', 'ANALYA (2)', 'ANAMARIA (2)', 'ANAMIKA (2)', 'ANANYA (2)', 'ANASTACIA (2)', 'ANASTASE (2)', 'ANASTASIA (2)', 'ANASTASIE (2)', 'ANASTASSIA (2)', 'ANASTASYA (2)', 'ANASTHASIA (2)', 'ANASTHASIE (2)', 'ANATHALIE (2)', 'ANATHILDE (2)', 'ANATOLE (2)', 'ANATOLIE (2)', 'ANATOLINE (2)', 'ANAYA (2)', 'ANAYAH (2)', 'ANAYS (2)', 'ANAÉ (2)', 'ANAË (2)', 'ANAËL (2)', 'ANAËLLE (2)', 'ANAÏA (2)', 'ANAÏS (2)', 'ANCELINE (2)', 'ANDIE (2)', 'ANDJALY (2)', 'ANDJELA (2)', 'ANDOCHE (2)', 'ANDRA (2)', 'ANDREA (2)', 'ANDREANE (2)', 'ANDREANNE (2)', 'ANDREEA (2)', 'ANDREIA (2)', 'ANDRELINE (2)', 'ANDRENA (2)', 'ANDRESE (2)', 'ANDRESIA (2)', 'ANDRESINE (2)', 'ANDRESSA (2)', 'ANDRETTE (2)', 'ANDREZE (2)', 'ANDRIJANA (2)', 'ANDRÉ (2)', 'ANDRÉA (2)', 'ANDRÉE (2)', 'ANDY (2)', 'ANELIA (2)', 'ANELIE (2)', 'ANELLA (2)', 'ANELYA (2)', 'ANELYSE (2)', 'ANEMONE (2)', 'ANESIE (2)', 'ANETTE (2)', 'ANEYA (2)', 'ANFAL (2)', 'ANFEL (2)', 'ANGE (2)', 'ANGE-MARIE (2)', 'ANGEL (2)', 'ANGELA (2)', 'ANGELE (2)', 'ANGELES (2)', 'ANGELIA (2)', 'ANGELICA (2)', 'ANGELIE (2)', 'ANGELIKA (2)', 'ANGELINA (2)', 'ANGELINE (2)', 'ANGELIQUA (2)', 'ANGELIQUE (2)', 'ANGELITA (2)', 'ANGELLA (2)', 'ANGELLE (2)', 'ANGELY (2)', 'ANGELYNA (2)', 'ANGELYNE (2)', 'ANGES (2)', 'ANGHJULA (2)', 'ANGHJULA-MARIA (2)', 'ANGHJULINA (2)', 'ANGIE (2)', 'ANGY (2)', 'ANGÈLE (2)', 'ANGÈLIQUE (2)', 'ANGÉLA (2)', 'ANGÉLINA (2)', 'ANGÉLINE (2)', 'ANGÉLIQUE (2)', 'ANH (2)', 'ANI (2)', 'ANIA (2)', 'ANIC (2)', 'ANICET (2)', 'ANICETTE (2)', 'ANICK (2)', 'ANIE (2)', 'ANIELA (2)', 'ANIELE (2)', 'ANIELLE (2)', 'ANIFA (2)', 'ANIK (2)', 'ANIKA (2)', 'ANILA (2)', 'ANIQUE (2)', 'ANISA (2)', 'ANISE (2)', 'ANISHA (2)', 'ANISSA (2)', 'ANISSAH (2)', 'ANISSIA (2)', 'ANITA (2)', 'ANITE (2)', 'ANITHA (2)', 'ANIYA (2)', 'ANJA (2)', 'ANJALI (2)', 'ANJALIE (2)', 'ANJALY (2)', 'ANJELA (2)', 'ANN (2)', 'ANNA (2)', 'ANNA-CHRISTINA (2)', 'ANNA-DEA (2)', 'ANNA-LESIA (2)', 'ANNA-LIA (2)', 'ANNA-LISA (2)', 'ANNA-LIVIA (2)', 'ANNA-LOU (2)', 'ANNA-MARIA (2)', 'ANNA-MARIE (2)', 'ANNA-ROSE (2)', 'ANNABEL (2)', 'ANNABELLA (2)', 'ANNABELLE (2)', 'ANNAEL (2)', 'ANNAELLE (2)', 'ANNAH (2)', 'ANNAICK (2)', 'ANNAIG (2)', 'ANNAIK (2)', 'ANNAIS (2)', 'ANNAÉ (2)', 'ANNAËLLE (2)', 'ANNAÏCK (2)', 'ANNAÏG (2)', 'ANNE (2)', 'ANNE-AYMONE (2)', 'ANNE-CAROLE (2)', 'ANNE-CAROLINE (2)', 'ANNE-CATHERINE (2)', 'ANNE-CHANTAL (2)', 'ANNE-CHARLOTTE (2)', 'ANNE-CHRISTELLE (2)', 'ANNE-CHRISTINE (2)', 'ANNE-CLAIRE (2)', 'ANNE-CLAUDE (2)', 'ANNE-CLÉMENCE (2)', 'ANNE-CÉCILE (2)', 'ANNE-CÉLINE (2)', 'ANNE-DOMINIQUE (2)', 'ANNE-ELISABETH (2)', 'ANNE-ELISE (2)', 'ANNE-EMILIE (2)', 'ANNE-EMMANUELLE (2)', 'ANNE-EVA (2)', 'ANNE-FLEUR (2)', 'ANNE-FLORE (2)', 'ANNE-FLORENCE (2)', 'ANNE-FRANCE (2)', 'ANNE-FRANÇOISE (2)', 'ANNE-FRÉDÉRIQUE (2)', 'ANNE-GAEL (2)', 'ANNE-GAELLE (2)', 'ANNE-GAËL (2)', 'ANNE-GAËLLE (2)', 'ANNE-HÉLÈNE (2)', 'ANNE-ISABELLE (2)', 'ANNE-JOSÉ (2)', 'ANNE-JULIE (2)', 'ANNE-KARINE (2)', 'ANNE-LAURE (2)', 'ANNE-LAURENCE (2)', 'ANNE-LINE (2)', 'ANNE-LISE (2)', 'ANNE-LORRAINE (2)', 'ANNE-LOUISE (2)', 'ANNE-LYSE (2)', 'ANNE-MAELLE (2)', 'ANNE-MARIE (2)', 'ANNE-MARINE (2)', 'ANNE-MICHÈLE (2)', 'ANNE-PASCALE (2)', 'ANNE-SANDRINE (2)', 'ANNE-SARAH (2)', 'ANNE-SOIZIC (2)', 'ANNE-SOLÈNE (2)', 'ANNE-SOPHIE (2)', 'ANNE-STÉPHANIE (2)', 'ANNE-SYLVIE (2)', 'ANNE-THÉRÈSE (2)', 'ANNE-VALÉRIE (2)', 'ANNE-VICTOIRE (2)', 'ANNE-VÉRONIQUE (2)', 'ANNE-YVONNE (2)', 'ANNEA (2)', 'ANNECIE (2)', 'ANNECY (2)', 'ANNELIESE (2)', 'ANNELINE (2)', 'ANNELISE (2)', 'ANNELLE (2)', 'ANNELORE (2)', 'ANNELYSE (2)', 'ANNEMARIE (2)', 'ANNETTE (2)', 'ANNI (2)', 'ANNIA (2)', 'ANNIC (2)', 'ANNICK (2)', 'ANNIE (2)', 'ANNIE-CHRISTINE (2)', 'ANNIE-CLAIRE (2)', 'ANNIE-CLAUDE (2)', 'ANNIE-FLORE (2)', 'ANNIE-FRANCE (2)', 'ANNIE-MARIE (2)', 'ANNIE-PAULE (2)', 'ANNIE-ROSE (2)', 'ANNIK (2)', 'ANNIKA (2)', 'ANNINE (2)', 'ANNIQUE (2)', 'ANNISE (2)', 'ANNISSA (2)', 'ANNITA (2)', 'ANNONCIA (2)', 'ANNONCIADE (2)', 'ANNONCIAT (2)', 'ANNONCIATION (2)', 'ANNOUK (2)', 'ANNUNZIATA (2)', 'ANNWEN (2)', 'ANNWENN (2)', 'ANNY (2)', 'ANNY-CLAUDE (2)', 'ANNYCK (2)', 'ANNYVONNE (2)', 'ANONYME (2)', 'ANOUCHKA (2)', 'ANOUCK (2)', 'ANOUK (2)', 'ANOUSHKA (2)', 'ANSELME (2)', 'ANTA (2)', 'ANTHEA (2)', 'ANTHELMETTE (2)', 'ANTHELMINE (2)', 'ANTHÉA (2)', 'ANTINEA (2)', 'ANTINÉA (2)', 'ANTOINE (2)', 'ANTOINETTE (2)', 'ANTOINISE (2)', 'ANTONELLA (2)', 'ANTONIA (2)', 'ANTONIE (2)', 'ANTONIETTA (2)', 'ANTONINA (2)', 'ANTONINE (2)', 'ANUSHKA (2)', 'ANY (2)', 'ANYA (2)', 'ANYSE (2)', 'ANYSSA (2)', 'ANZIZA (2)', 'ANÉLIA (2)', 'ANÉLYA (2)', 'AOUATEF (2)', 'AOUATIF (2)', 'AOUICHA (2)', 'AOUREGAN (2)', 'APOLINE (2)', 'APOLLINAIRE (2)', 'APOLLINE (2)', 'APOLLONIA (2)', 'APOLLONIE (2)', 'APOLONIE (2)', 'APPOLINA (2)', 'APPOLINAIRE (2)', 'APPOLINE (2)', 'APPOLLONIE (2)', 'APPOLONIE (2)', 'APRIL (2)', 'ARABA (2)', 'ARABELLA (2)', 'ARABELLE (2)', 'ARACELI (2)', 'ARAMATA (2)', 'ARAME (2)', 'ARANTXA (2)', 'ARBIA (2)', 'ARCADE (2)', 'AREEJ (2)', 'ARGENTINE (2)', 'ARGITXU (2)', 'ARIA (2)', 'ARIANA (2)', 'ARIANE (2)', 'ARIANNA (2)', 'ARIANNE (2)', 'ARIEL (2)', 'ARIELE (2)', 'ARIELLA (2)', 'ARIELLE (2)', 'ARIFE (2)', 'ARIGE (2)', 'ARIJ (2)', 'ARIJE (2)', 'ARIN (2)', 'ARINA (2)', 'ARINAS (2)', 'ARISHA (2)', 'ARISTA (2)', 'ARISTIDE (2)', 'ARIZONA (2)', 'ARJIN (2)', 'ARLENE (2)', 'ARLETE (2)', 'ARLETTE (2)', 'ARLETTY (2)', 'ARMANCE (2)', 'ARMANDA (2)', 'ARMANDE (2)', 'ARMANDINE (2)', 'ARMANTINE (2)', 'ARMEL (2)', 'ARMELE (2)', 'ARMELLE (2)', 'ARMIDE (2)', 'ARMINDA (2)', 'ARMONI (2)', 'ARMONIA (2)', 'ARMONIE (2)', 'ARMONY (2)', 'ARNAUDE (2)', 'AROUNY (2)', 'ARSENE (2)', 'ARTEMIS (2)', 'ARTEMISE (2)', 'ARTHEMISE (2)', 'ARTHUR (2)', 'ARTHURINE (2)', 'ARTÉMIS (2)', 'ARWA (2)', 'ARWEN (2)', 'ARWENN (2)', 'ARYA (2)', 'ARYAM (2)', 'ARYANA (2)', 'ARZU (2)', 'ASCENSION (2)', 'ASEEL (2)', 'ASEL (2)', 'ASHANTI (2)', 'ASHANTY (2)', 'ASHLEY (2)', 'ASHNA (2)', 'ASHVIKA (2)', 'ASIA (2)', 'ASIL (2)', 'ASIYA (2)', 'ASLI (2)', 'ASLIHAN (2)', 'ASMA (2)', 'ASMAA (2)', 'ASMAE (2)', 'ASMAHAN (2)', 'ASMAOU (2)', 'ASMIN (2)', 'ASMINA (2)', 'ASMINE (2)', 'ASMITHA (2)', 'ASNA (2)', 'ASSA (2)', 'ASSALA (2)', 'ASSANA (2)', 'ASSANATOU (2)', 'ASSATA (2)', 'ASSETA (2)', 'ASSETOU (2)', 'ASSIA (2)', 'ASSIL (2)', 'ASSILE (2)', 'ASSINA (2)', 'ASSITA (2)', 'ASSITAN (2)', 'ASSIYA (2)', 'ASSIYAH (2)', 'ASSMA (2)', 'ASSOMPTION (2)', 'ASSUNTA (2)', 'ASSYA (2)', 'ASSYAH (2)', 'ASSYL (2)', 'ASSYLE (2)', 'ASTA (2)', 'ASTAN (2)', 'ASTER (2)', 'ASTOU (2)', 'ASTREE (2)', 'ASTRID (2)', 'ASTRIDE (2)', 'ASTRÉE (2)', 'ASUNCION (2)', 'ASVIKA (2)', 'ASYA (2)', 'ATHALIA (2)', 'ATHANASE (2)', 'ATHANASIA (2)', 'ATHANASIE (2)', 'ATHENA (2)', 'ATHENAIS (2)', 'ATHENAÏS (2)', 'ATHINA (2)', 'ATHÉNA (2)', 'ATHÉNAÏS (2)', 'ATIKA (2)', 'ATTALE (2)', 'AUBANE (2)', 'AUBERI (2)', 'AUBERIE (2)', 'AUBERT (2)', 'AUBERTE (2)', 'AUBERTINE (2)', 'AUBIERGE (2)', 'AUBIN (2)', 'AUDE (2)', 'AUDE-EMMANUELLE (2)', 'AUDE-LINE (2)', 'AUDE-MARIE (2)', 'AUDELIA (2)', 'AUDELINE (2)', 'AUDETTE (2)', 'AUDRAY (2)', 'AUDREN (2)', 'AUDREY (2)', 'AUDRINA (2)', 'AUDÉLIA (2)', 'AUGUSTA (2)', 'AUGUSTE (2)', 'AUGUSTIN (2)', 'AUGUSTINA (2)', 'AUGUSTINE (2)', 'AURA (2)', 'AURANE (2)', 'AURE (2)', 'AUREA (2)', 'AUREANE (2)', 'AUREGAN (2)', 'AUREGANE (2)', 'AURELE (2)', 'AURELIA (2)', 'AURELIE (2)', 'AURELIENNE (2)', 'AURELINE (2)', 'AURELY (2)', 'AURETTE (2)', 'AURIA (2)', 'AURIANA (2)', 'AURIANE (2)', 'AURIANNA (2)', 'AURIANNE (2)', 'AURLANE (2)', 'AURORA (2)', 'AURORE (2)', 'AURYANE (2)', 'AURÉLIA (2)', 'AURÉLIE (2)', 'AURÉLIEN (2)', 'AUTOMNE (2)', 'AUXANE (2)', 'AUXILIA (2)', 'AVA (2)', 'AVELINE (2)', 'AVIGAEL (2)', 'AVIGAIL (2)', 'AVIGAÏL (2)', 'AVIT (2)', 'AVITAL (2)', 'AVIVA (2)', 'AVRIL (2)', 'AVRILLETTE (2)', 'AVSIN (2)', 'AWA (2)', 'AWATEF (2)', 'AWATIF (2)', 'AWEN (2)', 'AWENA (2)', 'AWENN (2)', 'AXEL (2)', 'AXELE (2)', 'AXELL (2)', 'AXELLE (2)', 'AXIANE (2)', 'AXÈLE (2)', 'AYA (2)', 'AYAH (2)', 'AYALA (2)', 'AYANA (2)', 'AYANAH (2)', 'AYANE (2)', 'AYANNA (2)', 'AYANNAH (2)', 'AYAT (2)', 'AYCHA (2)', 'AYDA (2)', 'AYDEN (2)', 'AYELE (2)', 'AYEM (2)', 'AYESHA (2)', 'AYETTE (2)', 'AYLA (2)', 'AYLANA (2)', 'AYLEE (2)', 'AYLEEN (2)', 'AYLIE (2)', 'AYLIN (2)', 'AYLINE (2)', 'AYLIZ (2)', 'AYMELINE (2)', 'AYMIE (2)', 'AYNA (2)', 'AYNUR (2)', 'AYO (2)', 'AYRA (2)', 'AYSE (2)', 'AYSEGUL (2)', 'AYSEL (2)', 'AYSENUR (2)', 'AYSHA (2)', 'AYSIMA (2)', 'AYSUN (2)', 'AYZA (2)', 'AZELIE (2)', 'AZELINE (2)', 'AZEMA (2)', 'AZENOR (2)', 'AZILIS (2)', 'AZILIZ (2)', 'AZILYS (2)', 'AZIZA (2)', 'AZIZAH (2)', 'AZRA (2)', 'AZYLIS (2)', 'AZZURA (2)', 'AZZURRA (2)', 'AZÉLIA (2)', 'AZÉLIE (2)', 'AZÉLINE (2)', 'AZÉNOR (2)', 'AÉLA (2)', 'AÉLIA (2)', 'AÉLYA (2)', 'AÉLYS (2)', 'AÉNOR (2)', 'AÉRIS (2)', 'AËLA (2)', 'AËLIA (2)', 'AËLIG (2)', 'AËLYA (2)', 'AËLYS (2)', 'AÏCHA (2)', 'AÏCHATA (2)', 'AÏCHATOU (2)', 'AÏDA (2)', 'AÏKO (2)', 'AÏLEEN (2)', 'AÏLY (2)', 'AÏNA (2)', 'AÏNARA (2)', 'AÏNHOA (2)', 'AÏNOA (2)', 'AÏSHA (2)', 'AÏSSA (2)', 'AÏSSATA (2)', 'AÏSSATOU (2)', 'AÏSSETOU (2)', 'AÏSSÉ (2)', 'AÏVY (2)', 'AÏZA (2)', 'BABETTE (2)', 'BABYLAS (2)', 'BADIA (2)', 'BADRA (2)', 'BAHAR (2)', 'BAHIA (2)', 'BAHIJA (2)', 'BAKHTA (2)', 'BALBINE (2)', 'BALKIS (2)', 'BALQIS (2)', 'BAMBA (2)', 'BAMBI (2)', 'BAMBY (2)', 'BANA (2)', 'BAPTISTINE (2)', 'BARAA (2)', 'BARBARA (2)', 'BARBE (2)', 'BARBERINE (2)', 'BARISA (2)', 'BARKA (2)', 'BARNABE (2)', 'BARNABEE (2)', 'BARTHA (2)', 'BARTHELEMY (2)', 'BASILE (2)', 'BASILIA (2)', 'BASILIDE (2)', 'BASMA (2)', 'BASMALA (2)', 'BASSMA (2)', 'BASTIENNE (2)', 'BATHILDE (2)', 'BATOUL (2)', 'BATSHEVA (2)', 'BAYA (2)', 'BAYAN (2)', 'BAYANE (2)', 'BAYENE (2)', 'BAZILE (2)', 'BAÏA (2)', 'BEATRICE (2)', 'BEATRIX (2)', 'BEATRIZ (2)', 'BEGONA (2)', 'BEGONIA (2)', 'BEIJA (2)', 'BEILA (2)', 'BEJNA (2)', 'BELINA (2)', 'BELINAY (2)', 'BELINDA (2)', 'BELKIS (2)', 'BELLA (2)', 'BELQIS (2)', 'BENEDICTA (2)', 'BENEDICTE (2)', 'BENEDITE (2)', 'BENITA (2)', 'BENJAMIN (2)', 'BENJAMINE (2)', 'BENOITE (2)', 'BENOÎT (2)', 'BERANGERE (2)', 'BEREN (2)', 'BERENGERE (2)', 'BERENICE (2)', 'BERFIN (2)', 'BERITAN (2)', 'BERIVAN (2)', 'BERNADETTE (2)', 'BERNADINE (2)', 'BERNARD (2)', 'BERNARDE (2)', 'BERNARDETTE (2)', 'BERNARDINE (2)', 'BERNICE (2)', 'BERTHA (2)', 'BERTHE (2)', 'BERTHEA (2)', 'BERTHILDE (2)', 'BERTHILE (2)', 'BERTHILIE (2)', 'BERTILDE (2)', 'BERTILE (2)', 'BERTILLE (2)', 'BERTIN (2)', 'BERTINA (2)', 'BERTINE (2)', 'BERTRANDE (2)', 'BERTRANE (2)', 'BERYL (2)', 'BESMA (2)', 'BETHSABEE (2)', 'BETINA (2)', 'BETSY (2)', 'BETTIE (2)', 'BETTINA (2)', 'BETTY (2)', 'BETUL (2)', 'BETÜL (2)', 'BEVERLEY (2)', 'BEVERLY (2)', 'BEYA (2)', 'BEYONCE (2)', 'BEYZA (2)', 'BIANCA (2)', 'BIBI (2)', 'BIBIANE (2)', 'BIDIA (2)', 'BIENAIMEE (2)', 'BILJANA (2)', 'BILKIS (2)', 'BILLIE (2)', 'BINE (2)', 'BINETA (2)', 'BINETOU (2)', 'BINTA (2)', 'BINTOU (2)', 'BISMA (2)', 'BLAISE (2)', 'BLAISINE (2)', 'BLANCA (2)', 'BLANCHE (2)', 'BLANDINE (2)', 'BLESSING (2)', 'BLEUEN (2)', 'BLEUENN (2)', 'BLEUETTE (2)', 'BLONDINE (2)', 'BLUE (2)', 'BLUETTE (2)', 'BLUMA (2)', 'BOCHRA (2)', 'BOJANA (2)', 'BOLESLAWA (2)', 'BONAVENTURE (2)', 'BONIFACE (2)', 'BONNE (2)', 'BONNIE (2)', 'BOUCHERA (2)', 'BOUCHRA (2)', 'BOYE (2)', 'BOZENA (2)', 'BRANDY (2)', 'BRENDA (2)', 'BRENDY (2)', 'BRIANA (2)', 'BRIANNA (2)', 'BRICE (2)', 'BRIDGET (2)', 'BRIGIDA (2)', 'BRIGITTE (2)', 'BRIHANNA (2)', 'BRITANIE (2)', 'BRITANNY (2)', 'BRITANY (2)', 'BRITHANY (2)', 'BRITNEY (2)', 'BRITTANY (2)', 'BRONISLAWA (2)', 'BROOKE (2)', 'BROOKLYN (2)', 'BRUNA (2)', 'BRUNAELLE (2)', 'BRUNE (2)', 'BRUNEHILDE (2)', 'BRUNELLA (2)', 'BRUNETTA (2)', 'BRUNETTE (2)', 'BRUNHILDE (2)', 'BRUNO (2)', 'BRYANA (2)', 'BRYANNA (2)', 'BTISSAM (2)', 'BTISSAME (2)', 'BUKET (2)', 'BULLE (2)', 'BURCU (2)', 'BUSRA (2)', 'BÉATRICE (2)', 'BÉLINDA (2)', 'BÉNÉDICTE (2)', 'BÉRANGÈRE (2)', 'BÉRENGÈRE (2)', 'BÉRYL (2)', 'BÉRÉNICE (2)', 'CAGLA (2)', 'CAITLIN (2)', 'CAITLINE (2)', 'CALI (2)', 'CALIA (2)', 'CALIE (2)', 'CALINE (2)', 'CALISTA (2)', 'CALIXTE (2)', 'CALLIE (2)', 'CALLIOPE (2)', 'CALLIOPÉ (2)', 'CALLIOPÉE (2)', 'CALLISTA (2)', 'CALLISTE (2)', 'CALLY (2)', 'CALOGERA (2)', 'CALY (2)', 'CALYPSO (2)', 'CALYSTA (2)', 'CAMELIA (2)', 'CAMELLIA (2)', 'CAMELYA (2)', 'CAMERON (2)', 'CAMILA (2)', 'CAMILIA (2)', 'CAMILLA (2)', 'CAMILLE (2)', 'CAMILLIA (2)', 'CAMILYA (2)', 'CAMYLLE (2)', 'CAMÉLIA (2)', 'CAMÉLYA (2)', 'CANAN (2)', 'CANDICE (2)', 'CANDIDA (2)', 'CANDIDE (2)', 'CANDIE (2)', 'CANDY (2)', 'CANDYCE (2)', 'CANDYS (2)', 'CANELLE (2)', 'CANNELLE (2)', 'CANSEL (2)', 'CANSU (2)', 'CAPUCINE (2)', 'CARA (2)', 'CARENE (2)', 'CARIMA (2)', 'CARINA (2)', 'CARINE (2)', 'CARINNE (2)', 'CARLA (2)', 'CARLA-MARIA (2)', 'CARLA-MARIE (2)', 'CARLINE (2)', 'CARLOTA (2)', 'CARLOTTA (2)', 'CARLY (2)', 'CARLYNE (2)', 'CARME (2)', 'CARMELA (2)', 'CARMELE (2)', 'CARMELIA (2)', 'CARMELIE (2)', 'CARMELINA (2)', 'CARMELINE (2)', 'CARMELITE (2)', 'CARMELLA (2)', 'CARMELLE (2)', 'CARMEN (2)', 'CARMENE (2)', 'CAROL (2)', 'CAROL-ANN (2)', 'CAROL-ANNE (2)', 'CAROLA (2)', 'CAROLANE (2)', 'CAROLANNE (2)', 'CAROLE (2)', 'CAROLE-ANNE (2)', 'CAROLINA (2)', 'CAROLINE (2)', 'CAROLL (2)', 'CAROLLE (2)', 'CAROLYN (2)', 'CAROLYNE (2)', 'CASANDRA (2)', 'CASILDA (2)', 'CASIMIERA (2)', 'CASIMIR (2)', 'CASIMIRA (2)', 'CASIMIRE (2)', 'CASSANDRA (2)', 'CASSANDRE (2)', 'CASSIA (2)', 'CASSIDIE (2)', 'CASSIDY (2)', 'CASSIE (2)', 'CASSIOPEE (2)', 'CASSIOPÉE (2)', 'CASSY (2)', 'CASTILLE (2)', 'CATALEYA (2)', 'CATALIA (2)', 'CATALINA (2)', 'CATALIYA (2)', 'CATALYA (2)', 'CATALYNA (2)', 'CATALÉYA (2)', 'CATARINA (2)', 'CATERINA (2)', 'CATHALEYA (2)', 'CATHARINA (2)', 'CATHELINE (2)', 'CATHELYNE (2)', 'CATHERINA (2)', 'CATHERINE (2)', 'CATHIA (2)', 'CATHIANA (2)', 'CATHIE (2)', 'CATHLEEN (2)', 'CATHY (2)', 'CATIA (2)', 'CATTLEYA (2)', 'CATTY (2)', 'CATY (2)', 'CAULINE (2)', 'CECILE (2)', 'CECILIA (2)', 'CECILIE (2)', 'CECILLE (2)', 'CEDELLA (2)', 'CEDRINE (2)', 'CELENA (2)', 'CELENE (2)', 'CELENIA (2)', 'CELENIE (2)', 'CELESTE (2)', 'CELESTINE (2)', 'CELIA (2)', 'CELIANA (2)', 'CELIANE (2)', 'CELIE (2)', 'CELINA (2)', 'CELINE (2)', 'CELINIE (2)', 'CELLIA (2

In [147]:
names

       annais  preusuel  sexe  nombre  annees    Id_Couleur
0        1900      ABEL     1     382    1900      ABEL (1)
1        1900   ABRAHAM     1       9    1900   ABRAHAM (1)
2        1900   ACHILLE     1     152    1900   ACHILLE (1)
3        1900  ACHILLES     1       4    1900  ACHILLES (1)
4        1900      ADAM     1       9    1900      ADAM (1)
...       ...       ...   ...     ...     ...           ...
257341   2020       ÉVA     2     156    2020       ÉVA (2)
257342   2020      ÉVAN     1      62    2020      ÉVAN (1)
257343   2020      ÉZIO     1      12    2020      ÉZIO (1)
257344   2020  ÉZÉCHIEL     1      11    2020  ÉZÉCHIEL (1)
257345   2020      ÖMER     1      24    2020      ÖMER (1)

[257346 rows x 6 columns]

In [148]:
print(mapping_couleurs)
names['Couleur_Hex'] = names['Id_Couleur'].map(mapping_couleurs)

{'AALIYA (2)': '#0a5b5b', 'AALIYAH (2)': '#14b7b7', 'AALYA (2)': '#47eaea', 'AALYAH (2)': '#a3f4f4', 'ABBIE (2)': '#0a5b5b', 'ABBY (2)': '#14b7b7', 'ABBY-GAËLLE (2)': '#47eaea', 'ABBYGAELLE (2)': '#a3f4f4', 'ABBYGAËLLE (2)': '#0a5b5b', 'ABDON (2)': '#14b7b7', 'ABDONIE (2)': '#47eaea', 'ABDONISE (2)': '#a3f4f4', 'ABEL (2)': '#0a5b5b', 'ABELIA (2)': '#14b6b7', 'ABELINE (2)': '#47e9ea', 'ABELLA (2)': '#a3f4f4', 'ABELLE (2)': '#0a5b5b', 'ABI (2)': '#14b6b7', 'ABIBA (2)': '#47e9ea', 'ABIBATA (2)': '#a3f4f4', 'ABIGAEL (2)': '#0a5b5b', 'ABIGAELLE (2)': '#14b6b7', 'ABIGAIL (2)': '#47e9ea', 'ABIGAËL (2)': '#a3f4f4', 'ABIGAËLLE (2)': '#0a5b5b', 'ABIGAÏL (2)': '#14b6b7', 'ABINAYA (2)': '#47e9ea', 'ABIR (2)': '#a3f4f4', 'ABIRA (2)': '#0a5b5b', 'ABISHA (2)': '#14b6b7', 'ABLA (2)': '#47e8ea', 'ABRAR (2)': '#a3f3f4', 'ABRIL (2)': '#0a5a5b', 'ABSA (2)': '#14b5b7', 'ABY (2)': '#47e8ea', 'ABYGAEL (2)': '#a3f3f4', 'ABYGAELLE (2)': '#0a5a5b', 'ABYGAËL (2)': '#14b5b7', 'ABYGAËLLE (2)': '#47e8ea', 'ACACIA (2)': '#a3f3f4', 'ACELYA (2)': '#0a5a5b', 'ACHILLE (2)': '#14b5b7', 'ACIA (2)': '#47e8ea', 'ACIL (2)': '#a3f3f4', 'ADA (2)': '#0a5a5b', 'ADALINE (2)': '#14b5b7', 'ADAM (2)': '#47e8ea', 'ADAMA (2)': '#a3f3f4', 'ADAME (2)': '#0a5a5b', 'ADDA (2)': '#14b4b7', 'ADDISON (2)': '#47e7ea', 'ADELA (2)': '#a3f3f4', 'ADELAIDE (2)': '#0a5a5b', 'ADELAÏDE (2)': '#14b4b7', 'ADELE (2)': '#47e7ea', 'ADELHEID (2)': '#a3f3f4', 'ADELIA (2)': '#0a5a5b', 'ADELIE (2)': '#14b4b7', 'ADELINA (2)': '#47e7ea', 'ADELINE (2)': '#a3f3f4', 'ADELPHINE (2)': '#0a5a5b', 'ADELYA (2)': '#14b4b7', 'ADELYNE (2)': '#47e7ea', 'ADIA (2)': '#a3f3f4', 'ADINA (2)': '#0a5a5b', 'ADINE (2)': '#14b4b7', 'ADIXIA (2)': '#47e7ea', 'ADIZA (2)': '#a3f2f4', 'ADJA (2)': '#0a595b', 'ADJARATOU (2)': '#14b3b7', 'ADJIA (2)': '#47e6ea', 'ADJILA (2)': '#a3f2f4', 'ADLINE (2)': '#0a595b', 'ADNA (2)': '#14b3b7', 'ADOLIE (2)': '#47e6ea', 'ADOLPHE (2)': '#a3f2f4', 'ADOLPHINE (2)': '#0a595b', 'ADONAI (2)': '#14b3b7', 'ADONAY (2)': '#47e6ea', 'ADRIANA (2)': '#a3f2f4', 'ADRIANE (2)': '#0a595b', 'ADRIANNA (2)': '#14b3b7', 'ADRIANNE (2)': '#47e6ea', 'ADRIEN (2)': '#a3f2f4', 'ADRIENNE (2)': '#0a595b', 'ADÈLE (2)': '#14b2b7', 'ADÉLAÏDE (2)': '#47e5ea', 'ADÉLIA (2)': '#a3f2f4', 'ADÉLIE (2)': '#0a595b', 'AEL (2)': '#14b2b7', 'AELA (2)': '#47e5ea', 'AELIA (2)': '#a3f2f4', 'AELIG (2)': '#0a595b', 'AELIS (2)': '#14b2b7', 'AELLE (2)': '#47e5ea', 'AELYS (2)': '#a3f2f4', 'AENOR (2)': '#0a595b', 'AERIS (2)': '#14b2b7', 'AERITH (2)': '#47e5ea', 'AERYN (2)': '#a3f2f4', 'AFAF (2)': '#0a595b', 'AFEF (2)': '#14b2b7', 'AFFOU (2)': '#47e5ea', 'AFIA (2)': '#a3f2f4', 'AFIDA (2)': '#0a585b', 'AFIFA (2)': '#14b1b7', 'AFNANE (2)': '#47e4ea', 'AFSANA (2)': '#a3f1f4', 'AGATA (2)': '#0a585b', 'AGATE (2)': '#14b1b7', 'AGATHA (2)': '#47e4ea', 'AGATHE (2)': '#a3f1f4', 'AGLAE (2)': '#0a585b', 'AGLAEE (2)': '#14b1b7', 'AGLAÉ (2)': '#47e4ea', 'AGNAN (2)': '#a3f1f4', 'AGNES (2)': '#0a585b', 'AGNESE (2)': '#14b1b7', 'AGNIELA (2)': '#47e4ea', 'AGNÈS (2)': '#a3f1f4', 'AGUSTINA (2)': '#0a585b', 'AH (2)': '#14b1b7', 'AHANA (2)': '#47e3ea', 'AHAVA (2)': '#a3f1f4', 'AHED (2)': '#0a585b', 'AHLAM (2)': '#14b0b7', 'AHLAME (2)': '#47e3ea', 'AHLEM (2)': '#a3f1f4', 'AHLEME (2)': '#0a585b', 'AHSEN (2)': '#14b0b7', 'AI (2)': '#47e3ea', 'AICHA (2)': '#a3f1f4', 'AICHAT (2)': '#0a585b', 'AICHATA (2)': '#14b0b7', 'AICHATOU (2)': '#47e3ea', 'AICHE (2)': '#a3f1f4', 'AIDA (2)': '#0a585b', 'AIDEE (2)': '#14b0b7', 'AIKO (2)': '#47e3ea', 'AILEEN (2)': '#a3f1f4', 'AILYS (2)': '#0a585b', 'AIMA (2)': '#14afb7', 'AIMEE (2)': '#47e2ea', 'AIMIE (2)': '#a3f0f4', 'AIMMEE (2)': '#0a575b', 'AIMY (2)': '#14afb7', 'AIMÉE (2)': '#47e2ea', 'AINA (2)': '#a3f0f4', 'AINARA (2)': '#0a575b', 'AINES (2)': '#14afb7', 'AINHOA (2)': '#47e2ea', 'AINOA (2)': '#a3f0f4', 'AINTZANE (2)': '#0a575b', 'AISHA (2)': '#14afb7', 'AISSA (2)': '#47e2ea', 'AISSATA (2)': '#a3f0f4', 'AISSATOU (2)': '#0a575b', 'AISSE (2)': '#14afb7', 'AISSETA (2)': '#47e2ea', 'AISSETOU (2)': '#a3f0f4', 'AIYA (2)': '#0a575b', 'AIYANA (2)': '#14aeb7', 'AIZA (2)': '#47e1ea', 'AJLA (2)': '#a3f0f4', 'AKILA (2)': '#0a575b', 'AKIMA (2)': '#14aeb7', 'AKSHA (2)': '#47e1ea', 'AKSHANA (2)': '#a3f0f4', 'AKSHARA (2)': '#0a575b', 'AKSHAYA (2)': '#14aeb7', 'ALAA (2)': '#47e1ea', 'ALAE (2)': '#a3f0f4', 'ALAIA (2)': '#0a575b', 'ALAIN (2)': '#14aeb7', 'ALAIS (2)': '#47e1ea', 'ALAITZ (2)': '#a3f0f4', 'ALANA (2)': '#0a575b', 'ALANIS (2)': '#14aeb7', 'ALANNAH (2)': '#47e0ea', 'ALAYA (2)': '#a3eff4', 'ALAYNA (2)': '#0a565b', 'ALAÏA (2)': '#14adb7', 'ALAÏS (2)': '#47e0ea', 'ALBA (2)': '#a3eff4', 'ALBAN (2)': '#0a565b', 'ALBANE (2)': '#14adb7', 'ALBANIE (2)': '#47e0ea', 'ALBERT (2)': '#a3eff4', 'ALBERTA (2)': '#0a565b', 'ALBERTE (2)': '#14adb7', 'ALBERTINA (2)': '#47e0ea', 'ALBERTINE (2)': '#a3eff4', 'ALBINA (2)': '#0a565b', 'ALBINE (2)': '#14adb7', 'ALCIDA (2)': '#47e0ea', 'ALCIDIE (2)': '#a3eff4', 'ALDA (2)': '#0a565b', 'ALDEGONDE (2)': '#14acb7', 'ALDINA (2)': '#47dfea', 'ALDJIA (2)': '#a3eff4', 'ALEA (2)': '#0a565b', 'ALEENA (2)': '#14acb7', 'ALEEYAH (2)': '#47dfea', 'ALEKSANDRA (2)': '#a3eff4', 'ALENA (2)': '#0a565b', 'ALESIA (2)': '#14acb7', 'ALESSA (2)': '#47dfea', 'ALESSANDRA (2)': '#a3eff4', 'ALESSIA (2)': '#0a565b', 'ALESSYA (2)': '#14acb7', 'ALETH (2)': '#47dfea', 'ALEV (2)': '#a3eff4', 'ALEX (2)': '#0a565b', 'ALEXA (2)': '#14acb7', 'ALEXANDRA (2)': '#47deea', 'ALEXANDRE (2)': '#a3eef4', 'ALEXANDRIE (2)': '#0a555b', 'ALEXANDRINA (2)': '#14abb7', 'ALEXANDRINE (2)': '#47deea', 'ALEXANE (2)': '#a3eef4', 'ALEXANNE (2)': '#0a555b', 'ALEXE (2)': '#14abb7', 'ALEXIA (2)': '#47deea', 'ALEXIANE (2)': '#a3eef4', 'ALEXIE (2)': '#0a555b', 'ALEXINA (2)': '#14abb7', 'ALEXINE (2)': '#47deea', 'ALEXIS (2)': '#a3eef4', 'ALEXY (2)': '#0a555b', 'ALEYA (2)': '#14abb7', 'ALEYNA (2)': '#47deea', 'ALFRED (2)': '#a3eef4', 'ALFREDA (2)': '#0a555b', 'ALFREDE (2)': '#14aab7', 'ALFREDINE (2)': '#47ddea', 'ALFRÉDA (2)': '#a3eef4', 'ALIA (2)': '#0a555b', 'ALIAH (2)': '#14aab7', 'ALIANA (2)': '#47ddea', 'ALICE (2)': '#a3eef4', 'ALICIA (2)': '#0a555b', 'ALICJA (2)': '#14aab7', 'ALICYA (2)': '#47ddea', 'ALIDA (2)': '#a3eef4', 'ALIENOR (2)': '#0a555b', 'ALIETTE (2)': '#14aab7', 'ALIMA (2)': '#47ddea', 'ALIMATA (2)': '#a3eef4', 'ALIMATOU (2)': '#0a555b', 'ALINA (2)': '#14aab7', 'ALINE (2)': '#47ddea', 'ALISA (2)': '#a3edf4', 'ALISE (2)': '#0a545b', 'ALISEA (2)': '#14a9b7', 'ALISEE (2)': '#47dcea', 'ALISHA (2)': '#a3edf4', 'ALISON (2)': '#0a545b', 'ALISONE (2)': '#14a9b7', 'ALISSA (2)': '#47dcea', 'ALISSIA (2)': '#a3edf4', 'ALISSON (2)': '#0a545b', 'ALISSYA (2)': '#14a9b7', 'ALISÉE (2)': '#47dcea', 'ALIX (2)': '#a3edf4', 'ALIXE (2)': '#0a545b', 'ALIXIA (2)': '#14a9b7', 'ALIYA (2)': '#47dcea', 'ALIYAH (2)': '#a3edf4', 'ALIZA (2)': '#0a545b', 'ALIZE (2)': '#14a9b7', 'ALIZEA (2)': '#47dbea', 'ALIZEE (2)': '#a3edf4', 'ALIZÉ (2)': '#0a545b', 'ALIZÉA (2)': '#14a8b7', 'ALIZÉE (2)': '#47dbea', 'ALIÉNOR (2)': '#a3edf4', 'ALLEGRA (2)': '#0a545b', 'ALLIA (2)': '#14a8b7', 'ALLIETTE (2)': '#47dbea', 'ALLISON (2)': '#a3edf4', 'ALLISSIA (2)': '#0a545b', 'ALLISSON (2)': '#14a8b7', 'ALLIYA (2)': '#47dbea', 'ALLIYAH (2)': '#a3edf4', 'ALLY (2)': '#0a545b', 'ALLYA (2)': '#14a8b7', 'ALLYAH (2)': '#47dbea', 'ALLYSON (2)': '#a3edf4', 'ALLYSSIA (2)': '#0a535b', 'ALMA (2)': '#14a7b7', 'ALMAS (2)': '#47daea', 'ALMILA (2)': '#a3ecf4', 'ALMINA (2)': '#0a535b', 'ALMIRA (2)': '#14a7b7', 'ALODIE (2)': '#47daea', 'ALOISE (2)': '#a3ecf4', 'ALONA (2)': '#0a535b', 'ALOYSE (2)': '#14a7b7', 'ALOÏSE (2)': '#47daea', 'ALPHENA (2)': '#a3ecf4', 'ALPHONSE (2)': '#0a535b', 'ALPHONSIA (2)': '#14a7b7', 'ALPHONSINE (2)': '#47daea', 'ALSACE (2)': '#a3ecf4', 'ALTHEA (2)': '#0a535b', 'ALTHÉA (2)': '#14a7b7', 'ALVA (2)': '#47daea', 'ALVINA (2)': '#a3ecf4', 'ALVINE (2)': '#0a535b', 'ALWENA (2)': '#14a6b7', 'ALWENN (2)': '#47d9ea', 'ALWENNA (2)': '#a3ecf4', 'ALWINE (2)': '#0a535b', 'ALYA (2)': '#14a6b7', 'ALYAH (2)': '#47d9ea', 'ALYANA (2)': '#a3ecf4', 'ALYANNA (2)': '#0a535b', 'ALYCE (2)': '#14a6b7', 'ALYCIA (2)': '#47d9ea', 'ALYETTE (2)': '#a3ecf4', 'ALYMA (2)': '#0a535b', 'ALYNA (2)': '#14a6b7', 'ALYNE (2)': '#47d9ea', 'ALYS (2)': '#a3ecf4', 'ALYSEE (2)': '#0a535b', 'ALYSHA (2)': '#14a5b7', 'ALYSON (2)': '#47d8ea', 'ALYSONE (2)': '#a3ebf4', 'ALYSSA (2)': '#0a525b', 'ALYSSIA (2)': '#14a5b7', 'ALYSSON (2)': '#47d8ea', 'ALYX (2)': '#a3ebf4', 'ALYXE (2)': '#0a525b', 'ALYZEE (2)': '#14a5b7', 'ALYZÉA (2)': '#47d8ea', 'ALYZÉE (2)': '#a3ebf4', 'ALZINA (2)': '#0a525b', 'ALZIRA (2)': '#14a5b7', 'ALZIRE (2)': '#47d8ea', 'ALÉNA (2)': '#a3ebf4', 'ALÉSSIA (2)': '#0a525b', 'AMAELLE (2)': '#14a5b7', 'AMAIA (2)': '#47d8ea', 'AMAL (2)': '#a3ebf4', 'AMALE (2)': '#0a525b', 'AMALIA (2)': '#14a4b7', 'AMALIE (2)': '#47d7ea', 'AMALYA (2)': '#a3ebf4', 'AMANA (2)': '#0a525b', 'AMANCE (2)': '#14a4b7', 'AMANDA (2)': '#47d7ea', 'AMANDE (2)': '#a3ebf4', 'AMANDINE (2)': '#0a525b', 'AMANE (2)': '#14a4b7', 'AMANI (2)': '#47d7ea', 'AMANIE (2)': '#a3ebf4', 'AMANTE (2)': '#0a525b', 'AMANTHE (2)': '#14a4b7', 'AMANTINE (2)': '#47d7ea', 'AMANY (2)': '#a3ebf4', 'AMARA (2)': '#0a525b', 'AMARIA (2)': '#14a4b7', 'AMARINE (2)': '#47d6ea', 'AMARYLLIS (2)': '#a3eaf4', 'AMAYA (2)': '#0a515b', 'AMAÏA (2)': '#14a3b7', 'AMBER (2)': '#47d6ea', 'AMBRE (2)': '#a3eaf4', 'AMBRINE (2)': '#0a515b', 'AMBROISE (2)': '#14a3b7', 'AMBROISINE (2)': '#47d6ea', 'AMEDEE (2)': '#a3eaf4', 'AMEDINE (2)': '#0a515b', 'AMEENA (2)': '#14a3b7', 'AMEL (2)': '#47d6ea', 'AMELA (2)': '#a3eaf4', 'AMELE (2)': '#0a515b', 'AMELIA (2)': '#14a3b7', 'AMELIE (2)': '#47d6ea', 'AMELINA (2)': '#a3eaf4', 'AMELINE (2)': '#0a515b', 'AMELLE (2)': '#14a2b7', 'AMELY (2)': '#47d5ea', 'AMELYA (2)': '#a3eaf4', 'AMELYNE (2)': '#0a515b', 'AMEN (2)': '#14a2b7', 'AMENA (2)': '#47d5ea', 'AMENI (2)': '#a3eaf4', 'AMI (2)': '#0a515b', 'AMICIE (2)': '#14a2b7', 'AMINA (2)': '#47d5ea', 'AMINAH (2)': '#a3eaf4', 'AMINAT (2)': '#0a515b', 'AMINATA (2)': '#14a2b7', 'AMINATOU (2)': '#47d5ea', 'AMINE (2)': '#a3eaf4', 'AMIRA (2)': '#0a515b', 'AMNA (2)': '#14a2b7', 'AMOUR (2)': '#47d5ea', 'AMPARO (2)': '#a3e9f4', 'AMY (2)': '#0a505b', 'AMYNA (2)': '#14a1b7', 'AMÉLIA (2)': '#47d4ea', 'AMÉLIE (2)': '#a3e9f4', 'AMÉLINE (2)': '#0a505b', 'AMÉLY (2)': '#14a1b7', 'AMÉLYA (2)': '#47d4ea', 'ANA (2)': '#a3e9f4', 'ANA-BELA (2)': '#0a505b', 'ANA-CRISTINA (2)': '#14a1b7', 'ANA-MARIA (2)': '#47d4ea', 'ANA-PAULA (2)': '#a3e9f4', 'ANABEL (2)': '#0a505b', 'ANABELA (2)': '#14a1b7', 'ANABELLA (2)': '#47d4ea', 'ANABELLE (2)': '#a3e9f4', 'ANABIA (2)': '#0a505b', 'ANAE (2)': '#14a0b7', 'ANAEE (2)': '#47d3ea', 'ANAEL (2)': '#a3e9f4', 'ANAELE (2)': '#0a505b', 'ANAELLE (2)': '#14a0b7', 'ANAHIDE (2)': '#47d3ea', 'ANAHIT (2)': '#a3e9f4', 'ANAHITA (2)': '#0a505b', 'ANAHÉ (2)': '#14a0b7', 'ANAIA (2)': '#47d3ea', 'ANAICK (2)': '#a3e9f4', 'ANAIG (2)': '#0a505b', 'ANAIK (2)': '#14a0b7', 'ANAIS (2)': '#47d3ea', 'ANAISE (2)': '#a3e9f4', 'ANAIZ (2)': '#0a505b', 'ANALIA (2)': '#14a0b7', 'ANALYA (2)': '#47d3ea', 'ANAMARIA (2)': '#a3e9f4', 'ANAMIKA (2)': '#0a4f5b', 'ANANYA (2)': '#149fb7', 'ANASTACIA (2)': '#47d2ea', 'ANASTASE (2)': '#a3e8f4', 'ANASTASIA (2)': '#0a4f5b', 'ANASTASIE (2)': '#149fb7', 'ANASTASSIA (2)': '#47d2ea', 'ANASTASYA (2)': '#a3e8f4', 'ANASTHASIA (2)': '#0a4f5b', 'ANASTHASIE (2)': '#149fb7', 'ANATHALIE (2)': '#47d2ea', 'ANATHILDE (2)': '#a3e8f4', 'ANATOLE (2)': '#0a4f5b', 'ANATOLIE (2)': '#149fb7', 'ANATOLINE (2)': '#47d2ea', 'ANAYA (2)': '#a3e8f4', 'ANAYAH (2)': '#0a4f5b', 'ANAYS (2)': '#149fb7', 'ANAÉ (2)': '#47d1ea', 'ANAË (2)': '#a3e8f4', 'ANAËL (2)': '#0a4f5b', 'ANAËLLE (2)': '#149eb7', 'ANAÏA (2)': '#47d1ea', 'ANAÏS (2)': '#a3e8f4', 'ANCELINE (2)': '#0a4f5b', 'ANDIE (2)': '#149eb7', 'ANDJALY (2)': '#47d1ea', 'ANDJELA (2)': '#a3e8f4', 'ANDOCHE (2)': '#0a4f5b', 'ANDRA (2)': '#149eb7', 'ANDREA (2)': '#47d1ea', 'ANDREANE (2)': '#a3e8f4', 'ANDREANNE (2)': '#0a4f5b', 'ANDREEA (2)': '#149eb7', 'ANDREIA (2)': '#47d1ea', 'ANDRELINE (2)': '#a3e8f4', 'ANDRENA (2)': '#0a4f5b', 'ANDRESE (2)': '#149db7', 'ANDRESIA (2)': '#47d0ea', 'ANDRESINE (2)': '#a3e7f4', 'ANDRESSA (2)': '#0a4e5b', 'ANDRETTE (2)': '#149db7', 'ANDREZE (2)': '#47d0ea', 'ANDRIJANA (2)': '#a3e7f4', 'ANDRÉ (2)': '#0a4e5b', 'ANDRÉA (2)': '#149db7', 'ANDRÉE (2)': '#47d0ea', 'ANDY (2)': '#a3e7f4', 'ANELIA (2)': '#0a4e5b', 'ANELIE (2)': '#149db7', 'ANELLA (2)': '#47d0ea', 'ANELYA (2)': '#a3e7f4', 'ANELYSE (2)': '#0a4e5b', 'ANEMONE (2)': '#149db7', 'ANESIE (2)': '#47d0ea', 'ANETTE (2)': '#a3e7f4', 'ANEYA (2)': '#0a4e5b', 'ANFAL (2)': '#149cb7', 'ANFEL (2)': '#47cfea', 'ANGE (2)': '#a3e7f4', 'ANGE-MARIE (2)': '#0a4e5b', 'ANGEL (2)': '#149cb7', 'ANGELA (2)': '#47cfea', 'ANGELE (2)': '#a3e7f4', 'ANGELES (2)': '#0a4e5b', 'ANGELIA (2)': '#149cb7', 'ANGELICA (2)': '#47cfea', 'ANGELIE (2)': '#a3e7f4', 'ANGELIKA (2)': '#0a4e5b', 'ANGELINA (2)': '#149cb7', 'ANGELINE (2)': '#47cfea', 'ANGELIQUA (2)': '#a3e7f4', 'ANGELIQUE (2)': '#0a4e5b', 'ANGELITA (2)': '#149bb7', 'ANGELLA (2)': '#47ceea', 'ANGELLE (2)': '#a3e6f4', 'ANGELY (2)': '#0a4d5b', 'ANGELYNA (2)': '#149bb7', 'ANGELYNE (2)': '#47ceea', 'ANGES (2)': '#a3e6f4', 'ANGHJULA (2)': '#0a4d5b', 'ANGHJULA-MARIA (2)': '#149bb7', 'ANGHJULINA (2)': '#47ceea', 'ANGIE (2)': '#a3e6f4', 'ANGY (2)': '#0a4d5b', 'ANGÈLE (2)': '#149bb7', 'ANGÈLIQUE (2)': '#47ceea', 'ANGÉLA (2)': '#a3e6f4', 'ANGÉLINA (2)': '#0a4d5b', 'ANGÉLINE (2)': '#149bb7', 'ANGÉLIQUE (2)': '#47ceea', 'ANH (2)': '#a3e6f4', 'ANI (2)': '#0a4d5b', 'ANIA (2)': '#149ab7', 'ANIC (2)': '#47cdea', 'ANICET (2)': '#a3e6f4', 'ANICETTE (2)': '#0a4d5b', 'ANICK (2)': '#149ab7', 'ANIE (2)': '#47cdea', 'ANIELA (2)': '#a3e6f4', 'ANIELE (2)': '#0a4d5b', 'ANIELLE (2)': '#149ab7', 'ANIFA (2)': '#47cdea', 'ANIK (2)': '#a3e6f4', 'ANIKA (2)': '#0a4d5b', 'ANILA (2)': '#149ab7', 'ANIQUE (2)': '#47cdea', 'ANISA (2)': '#a3e6f4', 'ANISE (2)': '#0a4d5b', 'ANISHA (2)': '#149ab7', 'ANISSA (2)': '#47ccea', 'ANISSAH (2)': '#a3e5f4', 'ANISSIA (2)': '#0a4c5b', 'ANITA (2)': '#1499b7', 'ANITE (2)': '#47ccea', 'ANITHA (2)': '#a3e5f4', 'ANIYA (2)': '#0a4c5b', 'ANJA (2)': '#1499b7', 'ANJALI (2)': '#47ccea', 'ANJALIE (2)': '#a3e5f4', 'ANJALY (2)': '#0a4c5b', 'ANJELA (2)': '#1499b7', 'ANN (2)': '#47ccea', 'ANNA (2)': '#a3e5f4', 'ANNA-CHRISTINA (2)': '#0a4c5b', 'ANNA-DEA (2)': '#1499b7', 'ANNA-LESIA (2)': '#47ccea', 'ANNA-LIA (2)': '#a3e5f4', 'ANNA-LISA (2)': '#0a4c5b', 'ANNA-LIVIA (2)': '#1498b7', 'ANNA-LOU (2)': '#47cbea', 'ANNA-MARIA (2)': '#a3e5f4', 'ANNA-MARIE (2)': '#0a4c5b', 'ANNA-ROSE (2)': '#1498b7', 'ANNABEL (2)': '#47cbea', 'ANNABELLA (2)': '#a3e5f4', 'ANNABELLE (2)': '#0a4c5b', 'ANNAEL (2)': '#1498b7', 'ANNAELLE (2)': '#47cbea', 'ANNAH (2)': '#a3e5f4', 'ANNAICK (2)': '#0a4c5b', 'ANNAIG (2)': '#1498b7', 'ANNAIK (2)': '#47cbea', 'ANNAIS (2)': '#a3e5f4', 'ANNAÉ (2)': '#0a4c5b', 'ANNAËLLE (2)': '#1498b7', 'ANNAÏCK (2)': '#47cbea', 'ANNAÏG (2)': '#a3e4f4', 'ANNE (2)': '#0a4b5b', 'ANNE-AYMONE (2)': '#1497b7', 'ANNE-CAROLE (2)': '#47caea', 'ANNE-CAROLINE (2)': '#a3e4f4', 'ANNE-CATHERINE (2)': '#0a4b5b', 'ANNE-CHANTAL (2)': '#1497b7', 'ANNE-CHARLOTTE (2)': '#47caea', 'ANNE-CHRISTELLE (2)': '#a3e4f4', 'ANNE-CHRISTINE (2)': '#0a4b5b', 'ANNE-CLAIRE (2)': '#1497b7', 'ANNE-CLAUDE (2)': '#47caea', 'ANNE-CLÉMENCE (2)': '#a3e4f4', 'ANNE-CÉCILE (2)': '#0a4b5b', 'ANNE-CÉLINE (2)': '#1497b7', 'ANNE-DOMINIQUE (2)': '#47caea', 'ANNE-ELISABETH (2)': '#a3e4f4', 'ANNE-ELISE (2)': '#0a4b5b', 'ANNE-EMILIE (2)': '#1497b7', 'ANNE-EMMANUELLE (2)': '#47c9ea', 'ANNE-EVA (2)': '#a3e4f4', 'ANNE-FLEUR (2)': '#0a4b5b', 'ANNE-FLORE (2)': '#1496b7', 'ANNE-FLORENCE (2)': '#47c9ea', 'ANNE-FRANCE (2)': '#a3e4f4', 'ANNE-FRANÇOISE (2)': '#0a4b5b', 'ANNE-FRÉDÉRIQUE (2)': '#1496b7', 'ANNE-GAEL (2)': '#47c9ea', 'ANNE-GAELLE (2)': '#a3e4f4', 'ANNE-GAËL (2)': '#0a4b5b', 'ANNE-GAËLLE (2)': '#1496b7', 'ANNE-HÉLÈNE (2)': '#47c9ea', 'ANNE-ISABELLE (2)': '#a3e4f4', 'ANNE-JOSÉ (2)': '#0a4b5b', 'ANNE-JULIE (2)': '#1496b7', 'ANNE-KARINE (2)': '#47c9ea', 'ANNE-LAURE (2)': '#a3e4f4', 'ANNE-LAURENCE (2)': '#0a4a5b', 'ANNE-LINE (2)': '#1495b7', 'ANNE-LISE (2)': '#47c8ea', 'ANNE-LORRAINE (2)': '#a3e3f4', 'ANNE-LOUISE (2)': '#0a4a5b', 'ANNE-LYSE (2)': '#1495b7', 'ANNE-MAELLE (2)': '#47c8ea', 'ANNE-MARIE (2)': '#a3e3f4', 'ANNE-MARINE (2)': '#0a4a5b', 'ANNE-MICHÈLE (2)': '#1495b7', 'ANNE-PASCALE (2)': '#47c8ea', 'ANNE-SANDRINE (2)': '#a3e3f4', 'ANNE-SARAH (2)': '#0a4a5b', 'ANNE-SOIZIC (2)': '#1495b7', 'ANNE-SOLÈNE (2)': '#47c8ea', 'ANNE-SOPHIE (2)': '#a3e3f4', 'ANNE-STÉPHANIE (2)': '#0a4a5b', 'ANNE-SYLVIE (2)': '#1495b7', 'ANNE-THÉRÈSE (2)': '#47c8ea', 'ANNE-VALÉRIE (2)': '#a3e3f4', 'ANNE-VICTOIRE (2)': '#0a4a5b', 'ANNE-VÉRONIQUE (2)': '#1494b7', 'ANNE-YVONNE (2)': '#47c7ea', 'ANNEA (2)': '#a3e3f4', 'ANNECIE (2)': '#0a4a5b', 'ANNECY (2)': '#1494b7', 'ANNELIESE (2)': '#47c7ea', 'ANNELINE (2)': '#a3e3f4', 'ANNELISE (2)': '#0a4a5b', 'ANNELLE (2)': '#1494b7', 'ANNELORE (2)': '#47c7ea', 'ANNELYSE (2)': '#a3e3f4', 'ANNEMARIE (2)': '#0a4a5b', 'ANNETTE (2)': '#1494b7', 'ANNI (2)': '#47c7ea', 'ANNIA (2)': '#a3e3f4', 'ANNIC (2)': '#0a4a5b', 'ANNICK (2)': '#1493b7', 'ANNIE (2)': '#47c6ea', 'ANNIE-CHRISTINE (2)': '#a3e2f4', 'ANNIE-CLAIRE (2)': '#0a495b', 'ANNIE-CLAUDE (2)': '#1493b7', 'ANNIE-FLORE (2)': '#47c6ea', 'ANNIE-FRANCE (2)': '#a3e2f4', 'ANNIE-MARIE (2)': '#0a495b', 'ANNIE-PAULE (2)': '#1493b7', 'ANNIE-ROSE (2)': '#47c6ea', 'ANNIK (2)': '#a3e2f4', 'ANNIKA (2)': '#0a495b', 'ANNINE (2)': '#1493b7', 'ANNIQUE (2)': '#47c6ea', 'ANNISE (2)': '#a3e2f4', 'ANNISSA (2)': '#0a495b', 'ANNITA (2)': '#1493b7', 'ANNONCIA (2)': '#47c6ea', 'ANNONCIADE (2)': '#a3e2f4', 'ANNONCIAT (2)': '#0a495b', 'ANNONCIATION (2)': '#1492b7', 'ANNOUK (2)': '#47c5ea', 'ANNUNZIATA (2)': '#a3e2f4', 'ANNWEN (2)': '#0a495b', 'ANNWENN (2)': '#1492b7', 'ANNY (2)': '#47c5ea', 'ANNY-CLAUDE (2)': '#a3e2f4', 'ANNYCK (2)': '#0a495b', 'ANNYVONNE (2)': '#1492b7', 'ANONYME (2)': '#47c5ea', 'ANOUCHKA (2)': '#a3e2f4', 'ANOUCK (2)': '#0a495b', 'ANOUK (2)': '#1492b7', 'ANOUSHKA (2)': '#47c5ea', 'ANSELME (2)': '#a3e2f4', 'ANTA (2)': '#0a495b', 'ANTHEA (2)': '#1492b7', 'ANTHELMETTE (2)': '#47c4ea', 'ANTHELMINE (2)': '#a3e1f4', 'ANTHÉA (2)': '#0a485b', 'ANTINEA (2)': '#1491b7', 'ANTINÉA (2)': '#47c4ea', 'ANTOINE (2)': '#a3e1f4', 'ANTOINETTE (2)': '#0a485b', 'ANTOINISE (2)': '#1491b7', 'ANTONELLA (2)': '#47c4ea', 'ANTONIA (2)': '#a3e1f4', 'ANTONIE (2)': '#0a485b', 'ANTONIETTA (2)': '#1491b7', 'ANTONINA (2)': '#47c4ea', 'ANTONINE (2)': '#a3e1f4', 'ANUSHKA (2)': '#0a485b', 'ANY (2)': '#1491b7', 'ANYA (2)': '#47c4ea', 'ANYSE (2)': '#a3e1f4', 'ANYSSA (2)': '#0a485b', 'ANZIZA (2)': '#1490b7', 'ANÉLIA (2)': '#47c3ea', 'ANÉLYA (2)': '#a3e1f4', 'AOUATEF (2)': '#0a485b', 'AOUATIF (2)': '#1490b7', 'AOUICHA (2)': '#47c3ea', 'AOUREGAN (2)': '#a3e1f4', 'APOLINE (2)': '#0a485b', 'APOLLINAIRE (2)': '#1490b7', 'APOLLINE (2)': '#47c3ea', 'APOLLONIA (2)': '#a3e1f4', 'APOLLONIE (2)': '#0a485b', 'APOLONIE (2)': '#1490b7', 'APPOLINA (2)': '#47c3ea', 'APPOLINAIRE (2)': '#a3e1f4', 'APPOLINE (2)': '#0a485b', 'APPOLLONIE (2)': '#1490b7', 'APPOLONIE (2)': '#47c3ea', 'APRIL (2)': '#a3e0f4', 'ARABA (2)': '#0a475b', 'ARABELLA (2)': '#148fb7', 'ARABELLE (2)': '#47c2ea', 'ARACELI (2)': '#a3e0f4', 'ARAMATA (2)': '#0a475b', 'ARAME (2)': '#148fb7', 'ARANTXA (2)': '#47c2ea', 'ARBIA (2)': '#a3e0f4', 'ARCADE (2)': '#0a475b', 'AREEJ (2)': '#148fb7', 'ARGENTINE (2)': '#47c2ea', 'ARGITXU (2)': '#a3e0f4', 'ARIA (2)': '#0a475b', 'ARIANA (2)': '#148fb7', 'ARIANE (2)': '#47c2ea', 'ARIANNA (2)': '#a3e0f4', 'ARIANNE (2)': '#0a475b', 'ARIEL (2)': '#148eb7', 'ARIELE (2)': '#47c1ea', 'ARIELLA (2)': '#a3e0f4', 'ARIELLE (2)': '#0a475b', 'ARIFE (2)': '#148eb7', 'ARIGE (2)': '#47c1ea', 'ARIJ (2)': '#a3e0f4', 'ARIJE (2)': '#0a475b', 'ARIN (2)': '#148eb7', 'ARINA (2)': '#47c1ea', 'ARINAS (2)': '#a3e0f4', 'ARISHA (2)': '#0a475b', 'ARISTA (2)': '#148eb7', 'ARISTIDE (2)': '#47c1ea', 'ARIZONA (2)': '#a3e0f4', 'ARJIN (2)': '#0a475b', 'ARLENE (2)': '#148eb7', 'ARLETE (2)': '#47c1ea', 'ARLETTE (2)': '#a3e0f4', 'ARLETTY (2)': '#0a465b', 'ARMANCE (2)': '#148db7', 'ARMANDA (2)': '#47c0ea', 'ARMANDE (2)': '#a3dff4', 'ARMANDINE (2)': '#0a465b', 'ARMANTINE (2)': '#148db7', 'ARMEL (2)': '#47c0ea', 'ARMELE (2)': '#a3dff4'

In [149]:
slider = alt.binding_range(min=1900, max=2020, step=1, name='year:')
year = alt.param(value=2004, bind=slider)
selection = alt.selection_point(fields=["annees"], bind=slider)

base = alt.Chart(names).mark_bar().encode(
    x = 'nombre:Q',
    y =alt.Y('preusuel:N', sort='-x'),
# color=alt.Color('couleur:N').scale(
#     domain=names_colores['couleur'].unique().tolist(), 
#     range=names_colores['couleur'].unique().tolist()
# ).legend(None)

# color=alt.Color(
#         'preusuel:N', 
#         scale=alt.Scale(range=ma_palette) # On applique notre palette ici
#     )

color=alt.Color(
        'Id_Couleur:N', # On colore basé sur notre identifiant unique
        # legend=alt.Legend(title="Prénoms (Sexe)"),
        # legend=None,
        scale=alt.Scale(range={"field": "Couleur_Hex"}
            # domain=list(mapping_couleurs.keys()),
            # range=list(mapping_couleurs.values())
        )    
)

# color=alt.Color(
#         'Couleur_Hex:N', 
#         scale=None # Dit à Altair : "Cette colonne contient déjà les vraies couleurs, utilise-les directement"
#     )

).add_params(
    year
).transform_filter(
    alt.datum.annais == alt.expr.toString(year),
).transform_window(    
    rank ='rank(nombre)',
    sort=[alt.SortField('nombre', order='descending')]
).transform_filter(
    alt.datum.rank <=20
).properties(
    width=600,
    height=400
)

base

alt.Chart(...)